### DISCUSSION TITLE
Tip: Linking the GivEVC Charging Rate to Predbat's equivalent

### DISCUSSION THREAD

**Discussion by DJBenson** [springfall2008/batpred#1256] [General]
For those with a GivEnergy EVC who are using the RESTful interface to control their charger, you will notice the app has the ability to "throttle" the charging rate in amps. There is a (semi) equivalent value in Predbat which controls the power in kW and I liked the idea of linking the two so that the rate adopts the value set from the charger which itself is pulled from the API using REST and converted to kW using the actual grid voltage.

![image](https://github.com/springfall2008/batpred/assets/1013909/da3c9ff7-77f4-49d9-a861-026fbd7ee48c)

![image](https://github.com/springfall2008/batpred/assets/1013909/4c9c1cac-ea7f-45ae-8913-06f5e4a3cb7e)

There's a few components to this so I'll break it down.

Firstly, you need to add a new sensor to pull the charging rate in from the API - copy/paste the below into your existing REST configuration for your EVC - if you've used Oliver "Speak to the Geek"'s method this should work with no changes;

```
- resource_template: 'https://api.givenergy.cloud/v1/ev-charger/{{ states("sensor.givenergy_ev_uuid") }}/commands/adjust-charge-power-limit/'
  scan_interval: 15
  headers:
    Authorization: !secret givenergy_apikey
    Accept: "application/json"
    Content-Type: "application/json"
  sensor:
    - name: "GivEnergy EV Charge Power Limit"
      unique_id: givenergy_ev_charge_power_limit
      value_template: "{{ value_json.data.value }}"
      device_class: "power"
      state_class: "measurement"
      unit_of_measurement: "A"
```

Next we will create a template sensor which converts the amps to kilowatts using your inverter grid voltage value. If you don't have an inverter you can simply hard-code it as 230 or whatever your mean grid voltage is. This sensor is also protected against the source going unknown which periodically happens when the REST call is made;

```
- trigger:
    - platform: state
      entity_id: sensor.givenergy_ev_charge_power_limit
      not_to: 
        - unknown
        - unavailable
  sensor:
  - name: "GivEnergy Linked Predbat Car Charging Rate"
    unique_id: 8d0828a1-4f98-4c65-bfbb-c9bc639df081
    state: "{{ ((states('sensor.givtcp_XXXXXXXXXX_grid_voltage')|int|round(0) * trigger.to_state.state|int)/1000)|round(1) }}"
    device_class: "power"
    state_class: "measurement"
    unit_of_measurement: "kW"
```

Finally you need an automation which keeps the two in sync;

```
alias: Sync Predbat charging rate to template sensor from GivEVC
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.givenergy_linked_predbat_car_charging_rate
    from: null
    to: null
    id: sync_charging_rate
action:
  - service: input_number.set_value
    target:
      entity_id: input_number.predbat_car_charging_rate
    data:
      value: "{{ states('sensor.givenergy_linked_predbat_car_charging_rate') }}"
mode: single
```

Optionally you can smooth out the grid voltage readings by putting them inside a statistics sensor;

```
- platform: statistics
  unique_id: 514ee2c8-f77d-4060-addf-ac60ccb2882b
  entity_id: sensor.givtcp_XXXXXXXXXX_grid_voltage
  name: Average Grid Voltage
  state_characteristic: mean
  max_age:
    hours: 4
```

...and update the sensor in the template sensor...

```
- trigger:
    - platform: state
      entity_id: sensor.givenergy_ev_charge_power_limit
      not_to: 
        - unknown
        - unavailable
  sensor:
  - name: "GivEnergy Linked Predbat Car Charging Rate"
    unique_id: 8d0828a1-4f98-4c65-bfbb-c9bc639df081
    state: "{{ ((states('sensor.average_grid_voltage')|int|round(0) * trigger.to_state.state|int)/1000)|round(1) }}"
    device_class: "power"
    state_class: "measurement"
    unit_of_measurement: "kW"
```

The Predbat value will now be kept in sync with the charging power from the GivEVC.
