### DISCUSSION TITLE
FoxESS Cloud integration

### DISCUSSION THREAD

**Discussion by davidarkemp** [springfall2008/batpred#1642] [General]
I've recently had a FoxESS system installed, and wanted to see what I could do with as little physical intervention as possible. If I think this looks like a viable solution moving forward (and already I'm realising I should have got more battery capacity) then I'll trail some cable around and connect it up via ModBus. 

I'd be really interested to get some feedback on this, as it's the first time I've used HA for anything more complicated than plug-and-play stuff.

With that I mind, I though I'd try to get https://github.com/macxq/foxess-ha working with predbat. 

* I'm using the solcast plugin rather than predbat.
* I'm taking the load from foxess cloud (which is via a CT clamp connected to the inverter) whilst I wait and see if I get an octopus mini

I'm not going to lie, it's been a bit of a struggle, but I think I've got something working... 

⚠️  I messed up the foxess-ha integration, so all of my sensors have a `_2` suffix. ⚠️ 

At the moment, I'm using the `foxess_pv_*` sensors, but I'm trying to understand whether the `foxess_solar_` sensors would be a better choice (they _seem_ to account for some invert losses). 

The last major hurdle I think I got was that `pv_power` is expected to be in watts, but foxess-ha delivers it in kilowatts. I have a template sensor that scales this to the correct value, but would be interested to hear.

```yaml
template:
  - sensor:
      - name: "PV Power in Watts"
        unit_of_measurement: "W"
        state: "{{ (states('sensor.foxess_pv_power_2') | float) * 1_000 }}"
```

With that in mind, I think the following provides the basis of what's needed for the apps.yaml:

```yaml
---
pred_bat:
  module: predbat
  class: PredBat

  prefix: predbat

  timezone: Europe/London

  currency_symbols:
    - "£"
    - "p"

  threads: auto

  #
  # Sensors, more than one can be specified and they will be summed up automatically
  load_today:
    - sensor.foxess_load_2
  import_today:
    - sensor.foxess_grid_consumption_2
  export_today:
    - sensor.foxess_feedin_2
  pv_today:
    - sensor.foxess_energy_generated_2

  #
  # Controls/status - must by 1 per inverter
  #
  num_inverters: 1

  inverter_type: FoxESS
  inverter:
    name: "FoxESS"
    has_rest_api: False
    has_mqtt_api: False
    has_service_api: True
    output_charge_control: "power"
    has_charge_enable_time: False
    has_discharge_enable_time: False
    has_target_soc: False
    has_reserve_soc: False
    charge_time_format: "S"
    charge_time_entity_is_option: False
    soc_units: "%"
    num_load_entities: 1
    has_ge_inverter_mode: False
    time_button_press: False
    clock_time_format: "%Y-%m-%d %H:%M:%S"
    write_and_poll_sleep: 2
    has_time_window: False
    support_charge_freeze: False
    support_discharge_freeze: False

  # Services to control charging/discharging
  charge_start_service:
    service: select.select_option
    entity_id: select.work_mode
    option: "Force Charge"
  charge_stop_service:
    service: select.select_option
    entity_id: select.work_mode
    option: "Self Use"
  discharge_start_service:
    service: select.select_option
    entity_id: select.work_mode
    option: "Force Discharge"


  # You should keep this section even when using REST as a fallback if it fails and for charge curve calculations
  charge_rate:
    - sensor.foxess_bat_charge_power_2
  discharge_rate:
    - sensor.foxess_bat_discharge_power_2
  battery_power:
    - sensor.foxess_bat_discharge_power_2
  pv_power:
    - sensor.pv_power_in_watts
  load_power:
    - sensor.foxess_load_power_2
  soc_kw:
    - sensor.foxess_bat_charge_2
  soc_percent:
    - sensor.foxess_bat_soc_2
  soc_max:
    - 5.18
  battery_rate_max:
    - 4200

  # Inverter max AC limit (one per inverter). E.g for a 3.6kw inverter set to 3600
  # If you have a second inverter for PV only please add the two values together
  inverter_limit:
    - 5000

  inverter_limit_charge:
    - 4200

  inverter_limit_discharge:
    - 4000

  # Inverter clock skew in minutes, e.g. 1 means it's 1 minute fast and -1 is 1 minute slow
  # Separate discharge skew for discharge windows only
  inverter_clock_skew_start: 0
  inverter_clock_skew_end: 0
  inverter_clock_skew_discharge_start: 0
  inverter_clock_skew_discharge_end: 0

  # Clock skew adjusts the Appdaemon time
  # 1 means add 1 minute to AppDaemon time, -1 takes it away
  clock_skew: 0

  # Set these to match solcast sensor names if not using the cloud interface
  # The regular expression (re:) makes the solcast bit optional
  # If these don't match find your own names in Home Assistant
  pv_forecast_today: re:(sensor.(solcast_|)(pv_forecast_|)forecast_today)
  pv_forecast_tomorrow: re:(sensor.(solcast_|)(pv_forecast_|)forecast_tomorrow)
  pv_forecast_d3: re:(sensor.(solcast_|)(pv_forecast_|)forecast_(day_3|d3))
  pv_forecast_d4: re:(sensor.(solcast_|)(pv_forecast_|)forecast_(day_4|d4))

  # Defines the number of cars modelled by the system, set to 0 for no car
  num_cars: 0

  octopus_intelligent_slot: "re:(binary_sensor.octopus_energy([0-9a-z_]+|)_intelligent_dispatching)"
  octopus_ready_time: "re:(time.octopus_energy([0-9a-z_]+|)_intelligent_ready_time)"
  octopus_charge_limit: "re:(number.octopus_energy([0-9a-z_]+|)_intelligent_charge_limit)"
  carbon_intensity: "re:(sensor.carbon_intensity_uk)"
  octopus_saving_session: "re:(binary_sensor.octopus_energy([0-9a-z_]+|)_saving_session(s|))"
  octopus_saving_session_octopoints_per_penny: 8
  metric_octopus_import: "re:(sensor.(octopus_energy_|)electricity_[0-9a-z]+_[0-9a-z]+_current_rate)"
  metric_octopus_export: "re:(sensor.(octopus_energy_|)electricity_[0-9a-z]+_[0-9a-z]+_export_current_rate)"

  # Standing charge in pounds, can be set to a sensor or manually entered (e.g. 0.50 is 50p)
  # The default below will pick up the standing charge from the Octopus Plugin
  # The standing charge only impacts the cost graphs and doesn't change the way Predbat plans
  # If you don't want to show the standing charge then just delete this line or set to zero
  metric_standing_charge: "re:(sensor.(octopus_energy_|)electricity_[0-9a-z]+_[0-9a-z]+_current_standing_charge)"

  # Can be used instead of the plugin to get import rates directly online
  # Overrides metric_octopus_import and rates_import
  # rates_import_octopus_url : "https://api.octopus.energy/v1/products/FLUX-IMPORT-23-02-14/electricity-tariffs/E-1R-FLUX-IMPORT-23-02-14-A/standard-unit-rates"
  # rates_import_octopus_url : "https://api.octopus.energy/v1/products/AGILE-FLEX-BB-23-02-08/electricity-tariffs/E-1R-AGILE-FLEX-BB-23-02-08-A/standard-unit-rates"

  # Overrides metric_octopus_export and rates_export
  # rates_export_octopus_url: "https://api.octopus.energy/v1/products/FLUX-EXPORT-BB-23-02-14/electricity-tariffs/E-1R-FLUX-EXPORT-BB-23-02-14-A/standard-unit-rates"
  # rates_export_octopus_url: "https://api.octopus.energy/v1/products/AGILE-OUTGOING-BB-23-02-28/electricity-tariffs/E-1R-AGILE-OUTGOING-BB-23-02-28-A/standard-unit-rates/"
  # rates_export_octopus_url: "https://api.octopus.energy/v1/products/OUTGOING-FIX-12M-BB-23-02-09/electricity-tariffs/E-1R-OUTGOING-FIX-12M-BB-23-02-09-A/standard-unit-rates/"

  # Import rates can be overridden with rate_import_override
  # Export rates can be overridden with rate_export_override
  # Use the same format as above, but a date can be included if it just applies for a set day (e.g. Octopus power ups)
  # This will override even the Octopus plugin rates if enabled
  #
  #rates_import_override:
  # -  date: '2023-09-10'
  #    start: '14:00:00'
  #    end: '14:30:00'
  #    rate: 112
  #    load_scaling: 0.8

  # For pv estimate, leave blank for central estimate, or add 10 for 10% curve (worst case) or 90 or 90% curve (best case)
  # If you use 10 then disable pv_metric10_weight below
  # pv_estimate: 10

  # Days previous is the number of days back to find historical load data
  # Recommended is 7 to capture day of the week but 1 can also be used
  # if you have more history you could use 7 and 14 (in a list) but the standard data in HA only lasts 10 days
  days_previous:
    - 7

  # Days previous weight can be used to control the weighting of the previous load points, the values are multiplied by their
  # weights and then divided through by the total weight. E.g. if you used 1 and 0.5 then the first value would have 2/3rd of the weight and the second 1/3rd
  # Include one value for each days_previous value, each weighting on a separate line.
  # If any days_previous's that are not given a weighting they will assume a default weighting of 1.
  days_previous_weight:
    - 1

  # Number of hours forward to forecast, best left as-is unless you have specific reason
  forecast_hours: 48

  # Specify the devices that notifies are sent to, the default is 'notify' which goes to all
  #notify_devices:
  #  - mobile_app_treforsiphone12_2

  # Battery scaling makes the battery smaller (e.g. 0.9) or bigger than its reported
  # If you have an 80% DoD battery that falsely reports it's kwh then set it to 0.8 to report the real figures
  # One per inverter
  battery_scaling:
    - 1.0

  # Can be used to scale import and export data, used for workarounds
  import_export_scaling: 1.0

  # Export triggers:
  # For each trigger give a name, the minutes of export needed and the energy required in that time
  # Multiple triggers can be set at once so in total you could use too much energy if all run
  # Creates an entity called 'binary_sensor.predbat_export_trigger_<name>' which will be turned On when the condition is valid
  # connect this to your automation to start whatever you want to trigger
  export_triggers:
    - name: "large"
      minutes: 60
      energy: 1.0
    - name: "small"
      minutes: 15
      energy: 0.25
```
