### DISCUSSION TITLE
LuxPower - How to set discharge SOC limit?

### DISCUSSION THREAD

**Discussion by s1dave-web** [springfall2008/batpred#1696] [Q&A]
New to batpred but have it working with my LuxPower 3.6kw Hybrid Inverter using guybw/LuxPython_DEV addon.

I can see it adjusting charge SOC limit and setting charge times to match the octopus low prices - great

I can see it also adjusting the force discharge times and enabling the discharge... but I do not see it manipulate the discharge SOC limit

Looking at the apps.yaml template the charge limit is set by this property:
  charge_limit:
    - number.lux_ac_battery_charge_level

I do not see any option for the discharge limit.

Should there not be another setting for the discharge limit such as:
 discharge_limit:
    - number.lux_forced_discharge_battery_level

Or is batpred controlling the discharge level using another method?

**Comment by gcoan** [comment]
Have you tried defining this extra entry in apps.yaml and see if it works?

**Comment by s1dave-web** [comment]
Added to apps.yaml - just need to wait till 5pm now when it will hopefully set the limit to 46%
![image](https://github.com/user-attachments/assets/5be1ed14-c760-4e04-95b9-cd7a1dce66a3)

I am also seeing this warning every 5 minutes in the logs:
Warn: Inverter 0: Using inverter type LuxPower - not all features are available

What features are not available?
Can the frequency of this warning be lowered?

**Comment by s1dave-web** [comment]
Adding discharge_limit seems to make no difference, I don't think the script knows it can set a discharge limit.

**Reply by raldred** [reply]
There is no `discharge_limit` option in batpred, you have to automate yourself. Batpred will control the `charge_limit` entity, for both charge and discharge, so you just need to sync these

**Comment by s1dave-web** [comment]
@springfall2008 does pretbat have the ability to set a discharge limit or does it just monitor/predict the discharge % for a given export window and stop when it gets to the intended limit?

**Reply by raldred** [reply]
@s1dave-web So our Lux inverters have separate charge and discharge target.
You need an automation to keep them in sync when using batpred since it uses a single target SOC entity

This automation will update your `lux_forced_discharge_battery_level` entity to match the `lux_ac_battery_charge_level` which batpred is controlling, if `predbat_exporting` is "on", if you've based your config from the lux template I contributed.


```
alias: Lux Set Discharge Target SOC (predbat)
description: ""
triggers:
  - entity_id:
      - binary_sensor.predbat_exporting
      - number.lux_ac_battery_charge_level
    trigger: state
conditions:
  - condition: state
    entity_id: binary_sensor.predbat_exporting
    state: "on"
actions:
  - action: number.set_value
    metadata: {}
    data:
      value: "{{ states('number.lux_ac_battery_charge_level') }}"
    target:
      entity_id: number.lux_forced_discharge_battery_level
mode: single

```
