### DISCUSSION TITLE
Setting up carbon intensity

### DISCUSSION THREAD

**Discussion by WyndStryke** [springfall2008/batpred#1872] [Q&A] [answered]
Hi,

I'm trying to set up the carbon intensity feature in the predbat planning, I think I'm most of the way there (the carbon_intensity_uk integration is picking up the carbon data today, and the forecast is being loaded into predbat), but it doesn't seem to be pulled into the actual plan as far as I can see.

If anybody spot what I'm missing, it'd be great :-)

This is predbat running in 'read only' mode, with charge&discharge control.

![carbon_intensity5](https://github.com/user-attachments/assets/d671df44-8ce4-45f6-bf26-d54979516be8)
![carbon_intensity4](https://github.com/user-attachments/assets/38a922f5-a36c-4613-bc0e-672929aaba4b)
![carbon_intensity3](https://github.com/user-attachments/assets/27963703-98d7-442c-afa3-7217dbb6cb4d)
![carbon_intensity2](https://github.com/user-attachments/assets/92d6ab66-952b-4c72-a07d-2740f0a438cc)
![carbon_intensity1](https://github.com/user-attachments/assets/fb4f4173-f5af-475d-a0f0-3386cbacf0b2)

The data looks like this:

```
current_period_from: 2025-01-13T15:00:00+00:00
current_period_to: 2025-01-13T16:00:00+00:00
current_period_forecast: 271.5
current_period_index: very high
optimal_window_from: 2025-01-14T00:00:00+00:00
optimal_window_to: 2025-01-14T04:00:00+00:00
optimal_window_forecast: 145.625
optimal_window_index: moderate
optimal_window_48_from: 2025-01-14T23:00:00+00:00
optimal_window_48_to: 2025-01-15T03:00:00+00:00
optimal_window_48_forecast: 195.375
optimal_window_48_index: high
unit: gCO2/kWh
postcode: XXX
forecast: 
- from: '2025-01-13T15:00:00+00:00'
  to: '2025-01-13T16:00:00+00:00'
  intensity: 271.5
  index: very high
  optimal: false
- from: '2025-01-13T16:00:00+00:00'
  to: '2025-01-13T17:00:00+00:00'
  intensity: 281
  index: very high
  optimal: false
- from: '2025-01-13T17:00:00+00:00'
  to: '2025-01-13T18:00:00+00:00'
  intensity: 283
  index: very high
  optimal: false
```

-Cheers
