### DISCUSSION TITLE
Adding Charge/Discharge Hold, and charge rate support for SolarEdge battery

### DISCUSSION THREAD

**Discussion by gpsmith** [springfall2008/batpred#2122] [General]
I went digging to try to work out how to do this after SE put a battery pause (for charge and discharge) in their app.  Based on a conversation over at the [SE modbus integration github](https://github.com/WillCodeForCats/solaredge-modbus-multi/discussions/785#discussioncomment-12524380), it seems that through the integration you can change the charge and discharge rates.

Given this, I believe that the following would be needed. Before I make the change and set predbat loose could someone in the know confirm this might be all I need to give predbat the ability to do it, or if I've missed something obvious? Thank you.

FYI I wasn't sure which is more optimal to have just a modified start and stop service, or also to deploy the `charge_freeze_service ` and `discharge_freeze_service `. Also do I need `discharge_stop_service ` given there isn't one in the current apps.yaml file?

```
support_charge_freeze: True  # Enables PredBat's charge hold capability
support_discharge_freeze: True

charge_start_service:
  - service: select.select_option
    entity_id: "select.solaredge_i1_storage_command_mode"
    option: "Charge from Solar Power and Grid"
    repeat: True
  - service: number.set_value
    entity_id: number.solaredge_i1_storage_charge_limit
    value: "{power}"  # PredBat injects the calculated charge rate
    repeat: True

charge_stop_service:
  - service: select.select_option
    entity_id: "select.solaredge_i1_storage_command_mode"
    option: "Maximize Self Consumption"
  - service: number.set_value
    entity_id: number.solaredge_i1_storage_charge_limit
    value: "{power}"  
    repeat: True

discharge_start_service:
  - service: select.select_option
    entity_id: "select.solaredge_i1_storage_command_mode"
    option: "Discharge to Maximize Export"
    repeat: True
  - service: number.set_value
    entity_id: number.solaredge_i1_storage_discharge_limit
    value: "{power}"  # PredBat injects calculated discharge rate
    repeat: True

discharge_stop_service:
  - service: select.select_option
    entity_id: "select.solaredge_i1_storage_command_mode"
    option: "Maximize Self Consumption"
    repeat: True
  - service: number.set_value
    entity_id: number.solaredge_i1_storage_discharge_limit
    value: "{power}" 
    repeat: True


```
