### DISCUSSION TITLE
Web interface in docker container

### DISCUSSION THREAD

**Discussion by simoncozens** [springfall2008/batpred#2166] [Q&A]
I've got batpred set up in a docker container using this configuration:

```yaml
  predbat:
    container_name: predbat
    image: nipar44/predbat_addon:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - /opt/hass/predbat-config:/config:rw
      - /etc/localtime:/etc/localtime:ro
```

Everything is working except the web interface. I thought it was because starting the HA web socket failed with this error:

```
2025-03-30 13:08:39.991959: Warn: Failed to decode response <Response [404]> from http://homeassistant.local:8123/addons/self/info
```

Because I'm using HA in docker, there's no addons, so that makes sense. Commenting out the `raise` line in

https://github.com/springfall2008/batpred/blob/78171e1f12e818c859ff1908309a8cd849e03815/apps/predbat/predbat.py#L1178-L1182

allows it to get a little further:

```
2025-03-30 13:08:39.993358: Creating task: <coroutine object WebInterface.start at 0x7f81813010>
2025-03-30 13:08:39.993921: Info: Start socket for url http://homeassistant.local:8123/api/websocket
Web interface started
2025-03-30 13:08:40.012179: Info: Web Socket active
```

But nothing is actually bound:

```
root@homeassistant:/opt/hass/predbat-config# telnet homeassistant.local 5052
Trying 172.17.0.1...
telnet: Unable to connect to remote host: Connection refused
root@homeassistant:/opt/hass/predbat-config# lsof -p 53117 | grep LISTEN
root@homeassistant:/opt/hass/predbat-config#
```

I'm pretty sure it's a problem my end (or maybe nobody's tried web interface + Docker container), but I'm totally confused about what it might be.
