### DISCUSSION TITLE
EON Next Smart Drive Tariff

### DISCUSSION THREAD

**Discussion by charliejvs** [springfall2008/batpred#2422] [General]
I recently posted an issue which I think I have got my head around now... maybe. And some of it possibly came down to being on the Eon Next Smart drive tariff which works in a very similar way to the intelligent octopus car tariff in such Eon control when the car charges. One of the things this seemed to do, was throw predbat out when the charging was undertaken outside of the main low price times. 

A few things these tariffs throw up. 
1) They offer cheep periods outside the main off-peak period. 
2) Charging can happen outside the off peak period. 

Is there any plan to look at having a way to integrate these new tariffs into predbat. I don't think EON has released an API to connect to this tariff but I could be wrong. The only one I can seem to find is once that knows the meter readings. 

If there is no current way to implement this, what is the best guidance for setup for these kind of tariffs. 

I have used the car charging now sensor in apps.yaml to possibly address point 2. Is this sensible?

**Comment by gcoan** [comment]
There are two ways of managing car charging in predbat, either Octopus Intelligent led or Predbat led.

If Eon are to control when the car charges then you'll have to turn switch.predbat_octopus_intelligent_charging on and then set car_charging_now so predbat can detect when the car is charging.
Does Eon allocate full 30 minute slots for car charging or can it be in bursts, e.g. 10 minutes?  If the latter then this'll be a problem as Predbat assumes the full 30 minute slot when the car charges is low rate.

You may get some warnings from predbat that it can't detect the octopus intelligent slots, and you might have to create a dummy sensor to set in apps.yaml to resolve this, but try it without and see what happens.

How does Eon tell you when it is charging the car and when there are cheaper rate slots?  If its an email then its possible to parse an email and convert it to an API, there are examples of other people that have done this, but its not trivial.
If there is no Eon API then it's going to be difficult for predbat to do much more.  At best you are limited to predbat detecting that the car is charging and then predbat start the battery charging  in the cheap slot.

**Reply by charliejvs** [reply]
From looking at the data, the charging slots can be smaller than 30min. But it seems the data from the meter is only polled at 30min intervals. So I assume that the full 30 min period the charging occurs in is at the lower rate. I’ll have to ask EON this. 

Similar to octopus eon uses an app to communicate with you. Showing the charging slots in the app only. So no notification. 

It would be good to ensure that these kind of charging tariffs are able to work effectively in predbat. At the very least on the scale that it takes the car charging into account when outside the normal window and doesn’t dump the house battery into the car.

**Reply by gcoan** [reply]
If you set car charging now then predbat can use that to detect the car is charging as per earlier.  

I would suggest turning switch.predbat_octopus_intelligent_charging on so predbat expects something else (not predbat) is planning the car charging.

And also set switch.predbat_car_charging_from_battery to false https://springfall2008.github.io/batpred/car-charging/#additional-car-charging-configurations so that predbat stops the battery discharging into the car

**Reply by charliejvs** [reply]
Sorry I have taken a while to respond back to this... not heavy car users and so had to for a few charges to get the settings to what I think are correct and observe the behaviour. 

here is my apps.yaml. and the config page. It seems to behave as I might expect. Please let me know if you think there are any glaringly obvious issues. 

[predbat config setup eon next.pdf](https://github.com/user-attachments/files/21242437/predbat.config.setup.eon.next.pdf)

[Predbat EON Next APPSYAML.txt](https://github.com/user-attachments/files/21242371/Predbat.EON.Next.APPSYAML.txt)

**Comment by jmfweather** [comment]
E.On neither knows nor cares what you consume in the off-peak period. I charge my solar battery and my EV in this off-peak period. 

For eON.Next you have to set manual rates. I use the following apps.yaml content for my eON.Next Drive V6 rates
```
 # Or set your actual rates across time for import and export
  # If start/end is missing it's assumed to be a fixed rate
  # Gaps are filled with 0
  rates_import:
     - start: "00:00:00"
       end: "06:59:59"
       rate: 6.7
     - start: "07:00:00"
       end: "23:59:59"
       rate: 26.32

  rates_export:
     - rate: 16.5

  rates_gas:
     - rate: 6.31
```
If your car or ev charger has an API then there should be sensors to use, via an HA integration, that can tell Predbat the state of charge, target charge level, and whether it is plugged in or not.

**Reply by gcoan** [reply]
I'd suggest you set your rate end times to :00:00 not as you have them. Predbat calculates rates in the half hour and your setup might have side effects 

This is what's in the documentation

**Reply by jmfweather** [reply]
Cheers. I've updated accordingly.

QQ: Are there any other Solax Inverter models supported or is it just a case that one Solax covers all Solax? FYI, I have an X1-IES with two batteries and a backup/island/eps unit.

**Reply by gcoan** [reply]
> QQ: Are there any other Solax Inverter models supported or is it just a case that one Solax covers all Solax? FYI, I have an X1-IES with two batteries and a backup/island/eps unit.

The key dependency is whether there's a HA integration for your inverter. If there is then it's likely predbat can be configured to use it https://springfall2008.github.io/batpred/inverter-setup/#i-want-to-add-an-unsupported-inverter-to-predbat

**Reply by jmfweather** [reply]
I'm using this integration (via HACS) - https://homeassistant-solax-modbus.readthedocs.io/en/latest/ and it's working well for my inverter. And the various entities are in my apps.yaml:
```
 # Solis specific parameters (these are based on https://github.com/wills106/homeassistant-solax-modbus)

  load_today:
    - sensor.solax_house_load
  import_today:
    - sensor.solax_today_s_import_energy
  export_today:
    - sensor.solax_today_s_export_energy
  pv_today:
    - sensor.solax_today_s_solar_energy

  battery_voltage:
    - sensor.solax_battery_1_voltage_charge

  # This is disabled by default in the Solax integration so it must be manually enabled.
  # inverter_time:
  #   - sensor.date_time

  # This is disabled by default in the Solax integration so it must be manually enabled.
  battery_power:
    - sensor.solax_battery_1_power_charge
  pv_power:
    - sensor.solax_pv_power_total
  grid_power:
    - sensor.solax_measured_power
    
  # For Solis inverters we need to add the bypass (backup) load to the main house load. If not used the load_power_1 can be commented out
  load_power:
    - sensor.solax_house_load
  load_power_1:
    - sensor.solax_eps_power

  soc_percent:
    - sensor.solax_battery_1_capacity_charge

  reserve:
    - number.solax_backup_discharge_min_soc

  battery_temperature:
    - sensor.solax_battery_1_temperature
    
#  battery_voltage:
#    - sensor.solax_battery_1_voltage_charge
  
  battery_min_soc:
    - number.solax_feedin_discharge_min_soc

  # With the Solax integration we need to press a button to send the time to
  charge_discharge_update_button:
    - button.solax_battery_awaken

```
There is no entity to read the inverter datetime. There is a **button.solax_sync_rtc** but I've no clear place for that in the apps.yaml
