### ISSUE TITLE
Goodwe inverter support

### ISSUE THREAD

**Issue by thibaultmol** [springfall2008/batpred#1000]
Do note: the defaut Goodwe integration on Home Assistant does not support manually setting charge/discharge. Only the experimental version of that integration does https://github.com/mletenay/home-assistant-goodwe-inverter

**Comment by springfall2008** [comment]
If you are willing to try it then it should be possible to configure

**Comment by Brkie** [comment]
Also intressed in support for goodwe, tell me if I can somehow help to make it possible

**Comment by gcoan** [comment]
> Also intressed in support for goodwe, tell me if I can somehow help to make it possible 

If you start from the template apps.yaml you'll need to work out what the input controls and services are to control your inverter/battery - to start it charging, stop charging, determine battery level, etc

see https://springfall2008.github.io/batpred/inverter-setup/#i-want-to-add-an-unsupported-inverter-to-predbat

If you get something working then we can incorporate it into the documentation.

**Comment by bpinto** [comment]
Has anyone had any success with this? I've started but there are so many configuration options on the `apps.yaml` that is hard to get started. 😅 

It would be nice if there was a template containing the basic information we need to provide to achieve different integration levels: monitor, etc.

I believe that the home assistant [integration](https://github.com/mletenay/home-assistant-goodwe-inverter) for goodwe should be capable of providing most of the information that is needed to connect.

If anyone familiar with Predbat could assist me with a basic yaml file, that would be great! 🤗 For what is worth, this is my [current attempt](https://github.com/bpinto/homelab/pull/24) that isn't working yet.

> Error: Inverter 0 unable to read charge window time as neither REST, charge_start_time or charge_start_hour are set

**Comment by gcoan** [comment]
I can help you get it working, reading the apps.yaml documentation (which is extraordinarily comprehensive) is a good starting point to understand what all the sensors are.

You'll really need to share full logfiles, and predbat debug files, not snippets as otherwise its extremely difficult to debug what is going on.

However from that logfile and your apps.yaml that you haven't followed the guidance I gave before about setting up apps.yaml for a new inverter type https://github.com/springfall2008/batpred/issues/1000#issuecomment-2639904919

Specifically I can see you have copied a givtcp apps.yaml (or the predbat default one), and filled in your inverter entities, which is good, but you haven't defined what inverter type you are using and the inverter capabilities so predbat assumes you have a givenergy inverter (type GE) and you haven't set the right config items for that.

Go back and follow the link above, define the inverter type (Goodwe), define its capabilities as per the documentation and then share your apps.yaml and logfile.

**Comment by bpinto** [comment]
@gcoan I appreciate your willingness to help me. :)

> Go back and follow the link above, define the inverter type (Goodwe), define its capabilities as per the documentation and then share your apps.yaml and logfile.

I've done that and I have a working setup right now! 🎉 I still need to go back to the documentation and the example `apps.yaml` to add missing functionality as well as double check the values I have used.

For now, I only two warnings that are coming from me incorrectly assigning a `sensor` instead of using a `number`.

**Comment by gcoan** [comment]
> I've done that and I have a working setup right now! 🎉

haha, its a matter of knowing what to look for, even though you provided no logs and little information .....

let us know how you get on

I did notice you made a lot of use of secret config settings, is there a reason for that?  Normally we just code everything in apps.yaml and people can then adjust for their inverter if its different from the authors inverter.
Would prefer you do that when you do share the working config as it makes it easier for others to reuse

**Comment by bpinto** [comment]
> I did notice you made a lot of use of secret config settings, is there a reason for that?

I am new to HA so I'm still figuring it out, my goal was to combine all of the hard-coded values in a single place so that it would be easy to know which values to change, however I think that is not a good idea in general since there are way too many hard coded values 😅 

I've changed my approach to code everything in the apps.yaml file. I appreciate this type of feedback! 👍

**Comment by bpinto** [comment]
@gcoan I have gone through most of the documentation and I've updated the code with my findings. I've also managed to successfully integrate the import rate with [Portuguese dynamic prices](https://github.com/joaofernandes/portuguese_energy_price_tracker_ha_integration).

I'd appreciate if you could review my [config](https://github.com/bpinto/homelab/blob/main/home-assistant/predbat/apps.yaml) in case I did something very wrong and if I'm being too conservative on the charge/discharge rates/limits.

Is there any configuration for battery health (SOH)? I couldn't find.

---

I intend to work on control mode next but I think this might be delayed since I need to understand how the goodwe integration works first.

**Comment by bpinto** [comment]
@gcoan I could use your help in this part as I'm not confident I fully understand what I have to do.

I'm working on enabling predbat on Control charge mode, you can see my code changes on this [PR](https://github.com/bpinto/homelab/pull/31). I am unsure about my changes and I have a few questions that I'd hope you could help me answering them.

The inverter has the following operation mode: `general, off_grid, backup, eco, eco_charge, eco_discharge`. For this implementation, I intend to use `general` and `eco_charge` modes only.

These are the options I have to configure the goodwe integration:

```
# GoodWe Depth of discharge (on-grid) // unit_of_measurement: %
number.goodwe_depth_of_discharge_on_grid

# GoodWe Eco mode power // unit_of_measurement: %
number.goodwe_eco_mode_power

# GoodWe Eco mode SoC // unit_of_measurement: %
number.goodwe_eco_mode_soc
```

My **potentially incorrect** understanding is that `number.goodwe_depth_of_discharge_on_grid` is applied when the inverter is on general mode (charging disabled). And that the other two numbers are meant to be used on eco_charge mode (charging enabled).

With that, do you think the changes on the [PR](https://github.com/bpinto/homelab/pull/31) are enough to let predbat control the charging cycles?

---

Regarding `inverter_limit` value, after reading my inverter [datasheet](https://en.goodwe.com/Ftp/EN/Downloads/Datasheet/GW_ES%20(14A)_Datasheet-EN.pdf) I believe its max charge rate is of 4600W? Should this value be set to 5000W or 4600W? I'm confused given there are too many reported values on the datasheet.

```yaml
  # Inverter max AC limit (one per inverter). E.g for a 3.6kw inverter set to 3600
  # Set this to your actual inverter limit
  inverter_limit:
    - 5000 # Should it be 5000 or 4600?
```

**Comment by gcoan** [comment]
> Regarding `inverter_limit` value, after reading my inverter [datasheet](https://en.goodwe.com/Ftp/EN/Downloads/Datasheet/GW_ES%20(14A)_Datasheet-EN.pdf) I believe its max charge rate is of 4600W? Should this value be set to 5000W or 4600W? I'm confused given there are too many reported values on the datasheet.

assuming you have the first one in the data sheetGW3648D-ES, you should set inverter_limit to the max AC your inverter can generate from PV, so 4600.  Battery charge/discharge limits are other config options



> These are the options I have to configure the goodwe integration:
> 
> ```
> # GoodWe Depth of discharge (on-grid) // unit_of_measurement: %
> number.goodwe_depth_of_discharge_on_grid
> 
> # GoodWe Eco mode power // unit_of_measurement: %
> number.goodwe_eco_mode_power
> 
> # GoodWe Eco mode SoC // unit_of_measurement: %
> number.goodwe_eco_mode_soc
> ```
> 
> My **potentially incorrect** understanding is that `number.goodwe_depth_of_discharge_on_grid` is applied when the inverter is on general mode (charging disabled). And that the other two numbers are meant to be used on eco_charge mode (charging enabled).

are those the only config options you have for the inverter?  If so, its going to be very simple in predbat terms.

my guess from reading the names and from how other inverters work with similar names:
- number.goodwe_depth_of_discharge_on_grid controls the percentage limit the inverter is to discharge down to when force discharging the battery. In predbat terminology this would be the **reserve**
-  number.goodwe_eco_mode_power sounds like the percentage power that the inverter uses when in eco mode.  So could be the inverter charge and discharge % rate, i.e. you can limit the charge/discharge rate.  In predbat this would be charge and discharge percentage
- number.goodwe_eco_mode_soc - that would be the current battery level (state of charge), its read not written to

And mode controls what the inverter does

What is recommended is that you learn what the different controls do when you manually control your inverter.  Do you have an app or web portal or screen on the inverter that you can use to control the inverter mode?
What I did for my own inverter was to learn how the inverter worked by manually initiating charges and discharges in the inverter app and seeing how the inverter controls in HA changed as a result.

My guess for your inverter is:

start_charge:
- set number.goodwe_eco_mode_power to 100 (full rate charge)
- set mode to eco_charge

stop_charge:
- set mode to general

Looks like you have come to a similar conclusion about eco_mode_power controlling the charge rate.  
But rather than creating a custom sensor to convert to/from watts you should be able to directly use charge_rate_percent https://springfall2008.github.io/batpred/apps-yaml/#chargedischarge-rate

you can comment all the car_charging_planned and similar stuff out of apps.yaml since you don't have an EV configured

in your config I see you have set 

has_reserve_soc: False

I think you can set this to true as number.goodwe_depth_of_discharge_on_grid does that (maybe)

in your apps.yaml, it is similar to what I suggested:

```
  charge_start_service:
    - service: select.select_option
      entity_id: "select.goodwe_inverter_operation_mode"
      option: eco_charge
    - delay:
        seconds: 10
    - service: number.set_value
      entity_id: "number.custom_goodwe_eco_mode_power_watts"
      value: "{power}"
    - delay:
        seconds: 10
    - service: number.set_value
      entity_id: "number.goodwe_eco_mode_soc"
      value: "{target_soc}"
```

my guess is that eco_mode_soc was read only, obviously you need to confirm this.  If it is writeable then you need to set has_target_soc to True and configure 

I would recommend that you reverse the order of commands, set the soc (if you can) and the power first, before changing the mode

But actually you can make it even simpler

configure charge_limit to be number.goodwe_eco_mode_soc
https://springfall2008.github.io/batpred/apps-yaml/#schedule

and charge_rate_percent to be  number.goodwe_eco_mode_power

and predbat will set these automatically, then you just need to set the mode in the control charge section

BTW the 'delay' option isn't recognised by predbat.  I did propose it, and coded it up, but it wasn't needed so its not a command predbat currently recognises

getting there

**Comment by bpinto** [comment]
> assuming you have the first one in the data sheetGW3648D-ES, you should set inverter_limit to the max AC your inverter can generate from PV, so 4600. Battery charge/discharge limits are other config options

Ooops, sorry, I should have been explicit about the model. Mine is the second on the data sheet, the GW5048D-ES which is labeled as a 5kW inverter.

With this information, would you mind checking again what value I should use? 🙏 

> are those the only config options you have for the inverter? If so, its going to be very simple in predbat terms.

Other inverters have more options, but mine is rather limited. These are all the non-sensors I could find coming from the goodwe integrator:

```
number.goodwe_depth_of_discharge_on_grid // %
number.goodwe_eco_mode_power // %
number.goodwe_eco_mode_soc // %
number.goodwe_fast_charging_soc // %
number.goodwe_grid_export_limit // W

select.goodwe_inverter_operation_mode // general, off_grid, backup, eco, eco_charge, eco_discharge

switch.goodwe_backup_supply // boolean
switch.goodwe_fast_charging_switch // boolean
switch.goodwe_grid_export_limit_switch // boolean
```

I can't see any fast charging related information on my inverter configuration (app / web app), so I haven't touched that option.

> What is recommended is that you learn what the different controls do when you manually control your inverter. Do you have an app or web portal or screen on the inverter that you can use to control the inverter mode?
What I did for my own inverter was to learn how the inverter worked by manually initiating charges and discharges in the inverter app and seeing how the inverter controls in HA changed as a result.

Yes, I do have one. I have been doing the same for testing the setup. As it is, I do have predbat controlling charging of my batteries but I'm going to apply your suggestions to make the integration better and I'm going to check it's doing the right thing on my inverter app side.

> has_reserve_soc: False
I think you can set this to true as number.goodwe_depth_of_discharge_on_grid does that (maybe)

If I understand what you are proposing here is that I could make these two changes:

```yaml
has_reserve_soc: True
reserve: goodwe_depth_of_discharge_on_grid
```

Would I need to do any further changes to the configuration?

Like the `number.goodwe_fast_charging_soc` above I can't see this on my goodwe app either. I have seen screenshots online from other goodwe users where they have access to different information than I have on the same app. I am going to perform a firmware upgrade soon and see if that brings any new options to the inverter app. I won't try to use reserve unless that becomes an option on the inverter app.

> my guess is that eco_mode_soc was read only, obviously you need to confirm this. If it is writeable then you need to set has_target_soc to True and configure

Predbat has been successfully updating that value, I see it changing to the correct value when it holds charge (e.g. 29%) and then performs a full a charge (100%). I'm going to test the `charge_limit` + `has_target_soc` combo however.

> But actually you can make it even simpler

Oh that's great! I'll be testing these proposed [changes](https://github.com/bpinto/homelab/pull/41/changes) today!

> BTW the 'delay' option isn't recognised by predbat. I did propose it, and coded it up, but it wasn't needed so its not a command predbat currently recognises

Oh 😅 good to know! Thanks to your proposal above I don't actually need any of that anymore :)

**Comment by bpinto** [comment]
One thing I don't know yet how to handle is "Hold Charge". For instance, at this moment predbat has it enabled and set it to 86%, however to enable it, it executes the `charge_start_service` which sets my inverter mode to "eco_charge". On this mode, my inverter will **not** consume any power from the battery.

<img width="766" height="115" alt="Image" src="https://github.com/user-attachments/assets/f6017843-ff8b-41d5-a468-06935dc0c3ba" />

**Comment by gcoan** [comment]
> One thing I don't know yet how to handle is "Hold Charge". For instance, at this moment predbat has it enabled and set it to 86%, however to enable it, it executes the charge_start_service which sets my inverter mode to "eco_charge". On this mode, my inverter will not consume any power from the battery.
> 
> 

that is fine there is no special processing for hold charge

read the description of the different predbat modes https://springfall2008.github.io/batpred/what-does-predbat-do/#predbat-modes

hold and freeze charge are a charge to the current SoC level, so they set charge mode but a SoC target.

in this particular case the target 86% is lower than the current SoC 97% so predbat expects the battery to be used until it gets down to 86%.  In reality this won't happen (I think the same happens on my inverter when its set to charge mode it can't discharge), and predbat will just recalculate when the plan doesn't quite match reality

**Comment by bpinto** [comment]
What is the difference between `battery_min_soc` and `reserve`?

> **battery_min_soc** - When set limits the target SoC% setting for charge and discharge to a minimum percentage value
> **reserve** - sensor name for the reserve SoC % setting. The reserve SoC is the lower limit target % to discharge the battery down to.

**Comment by gcoan** [comment]
They are different parts that work together 

Reserve is an entry in apps.yaml with the inverter sensor name for the lower discharge Soc limit, to discharge down to 

Battery min Soc is an input number entity in HA you configure to the minimum value to be set in the reserve entity, or the lowest Soc level that your inverter can access. So I set my minimum to 4 as the lowest 4% isn't usable. For some inverters it's 10%

**Comment by bpinto** [comment]
Hmm, the `reserve` can also reference a number (writeable), right? And predbat will update it.

That got me thinking about the "Hold Charge" implementation. If my thinking is correct, then when predbat wants to enable "Hold Charge" then it will update this `reserve` value as the inverter would guarantee that the battery will not drain below that value, but it should not trigger `charge_start_service` as we are not charging and because that, in my case, causes the inverter to **not** discharge from the battery.

What do you think? Am I missing something? 

---

I believe [this](https://github.com/springfall2008/batpred/blob/40dfbef80a59ac530c31a8e495ff612de1964fd0/apps/predbat/execute.py#L204-L225) is where hold charge is being handled, however unless I'm missing something it's not correctly [handling](https://github.com/springfall2008/batpred/blob/40dfbef80a59ac530c31a8e495ff612de1964fd0/apps/predbat/execute.py#L204) the scenario above where my battery SoC was 97% but the hold charge was set to 86% as the difference from `SoC` was > 1%.

**Comment by dmacwalter** [comment]
Hi @bpinto  have you had a look at https://github.com/mletenay/home-assistant-goodwe-inverter ?

This now gives you EMS support. I think this is a better solution for your requirements, although haven't explored how to integrate this into predbat yet. ![image](https://github.com/user-attachments/assets/764c3ec7-71d7-4cdd-9412-2e9bb3727134)

**Comment by bpinto** [comment]
@dmacwalter yep! I have been using it 👍 

Unfortunately afaik my inverter doesn't have EMS support so I'm left with the basic modes only. I will be performing a firmware upgrade soon though, but from a quick research I don't think it will change anything.

**Comment by gcoan** [comment]
> Hmm, the reserve can also reference a number (writeable), right? And predbat will update it.

correct, that is how reserve works in predbat

> That got me thinking about the "Hold Charge" implementation. If my thinking is correct, then when predbat wants to enable "Hold Charge" then it will update this reserve value as the inverter would guarantee that the battery will not drain below that value, but it should not trigger charge_start_service as we are not charging and because that, in my case, causes the inverter to not discharge from the battery.
>
> What do you think? Am I missing something?

I'd have to check the code to be 100% sure but predbat expects the reserve to hold the battery level. Does your inverter have target SoC for charge-to?  I'm not 100% sure but I think predbat would issue a start charge though to charge to the hold charge target.
I don't get a lot of hold charges on my plan but when I do, lie this morning, I see the inverter continuing to charge above the target:
![image](https://github.com/user-attachments/assets/9cc02e14-2697-4e19-abec-918782d187ce)

In my case I think this is the inverter not doing what predbat instructs, so I just live with it.
 
> I believe this is where hold charge is being handled, however unless I'm missing something it's not correctly handling the scenario above where my battery SoC was 97% but the hold charge was set to 86% as the difference from SoC was > 1%.

86% is the minimum level the battery should hold at as far as predbat is concerned (to meet the plan).

So what happened with your inverter when predbat issued a hold charge with reserve lower than current soc?

**Comment by bpinto** [comment]
> I'd have to check the code to be 100% sure but predbat expects the reserve to hold the battery level. Does your inverter have target SoC for charge-to? I'm not 100% sure but I think predbat would issue a start charge though to charge to the hold charge target.

My inverter has a target SoC for charge-to as well as a DoD. Right now I've got predbat configured to set both values, DoD is set through `reserve`.

> So what happened with your inverter when predbat issued a hold charge with reserve lower than current soc?

Since predbat triggered a `charge_start_service` then my inverter mode changed from General mode (that allows battery to be discharged) to Eco Charge Mode (which does not allow the battery to be discharged).

I'm not familiar with python, but I'll see if I can run the test suite of this project locally and then try to create a reproducible test scenario for my case. Looking at the [code](https://github.com/springfall2008/batpred/blob/40dfbef80a59ac530c31a8e495ff612de1964fd0/apps/predbat/execute.py#L204-L225), it seems to me that we need to adjust it so that charge mode isn't enabled when the target_soc is higher than the current soc, but I'm not familiar with all the scenarios it is trying to handle so most likely I'm missing some context.

> I don't get a lot of hold charges on my plan but when I do, lie this morning, I see the inverter continuing to charge above the target:

Could you confirm if during the period of Hold Charge that your inverter mode was changed to your Charge mode? I think you are experiencing the same thing that I am, and I believe that it could be fixed.

I don't understand why "G Control Target SOC" changed during the "Hold Charge" period. I was expecting your "G Control Battery Power Reserve" to have been updated instead.

**Comment by bpinto** [comment]
@gcoan This is what I had in mind, but I ran the test suite and a lot of tests fail with this, I have tried to understand the tests but there are a lot of abstractions that make it hard for newcomers to understand. 😅 

```diff
> diff --git a/apps/predbat/execute.py b/apps/predbat/execute.py
index e57baa6..a43d2ef 100644
--- a/apps/predbat/execute.py
+++ b/apps/predbat/execute.py
@@ -201,7 +201,7 @@ class Execute:
                                 status = "Hold charging"
                                 self.log("Inverter {} Hold charging as SoC {}% is above target SoC {}% set_discharge_during_charge {}".format(inverter.id, self.soc_percent, dp0(target_soc), self.set_discharge_during_charge))
 
-                                if (target_soc < 100.0) and (abs(inverter.soc_percent - target_soc) <= 1.0):
+                                if (target_soc < 100.0) and (inverter.soc_percent >= target_soc):
                                     # If we are within 1% of the target but not at 100% then we can hold charge
                                     # otherwise keep charging enabled
                                     if self.set_soc_enable and ((self.set_reserve_enable and self.set_reserve_hold and inverter.reserve_max >= inverter.soc_percent) or inverter.inv_has_timed_pause):
```

For what is worth, I think the logic used to be similar to what I'm proposing but it was changed in https://github.com/springfall2008/batpred/pull/1555

**Comment by bpinto** [comment]
@gcoan do you have more context on the reason for that code to be `(abs(inverter.soc_percent - target_soc) <= 1.0)` instead of `(inverter.soc_percent >= target_soc)` like it, apparently, was in the past?

I feel like this is a bug on the existing "Hold charging" code that is causing many inverters to not follow the plan that predbat has intended - as the battery is not being used.

I could create a separate issue if you think that would be a more appropriate channel.

**Comment by RampouchCZ** [comment]
Hi, sorry to hijack this thread, I have a quick question on the current status of GoodWe support. I’m looking at the new **GoodWe ESA** (not just their inverters) system and trying to understand if it can be properly integrated with Predbat for local-only control (no cloud dependency). Goodwe is currently not integrated with variable tariffs in UK, so predbat would be a must.

I’ve seen HA supports local monitoring and Modbus TCP exists, but it’s unclear how much write/control capability is actually available for Predbat to manage charging behaviour. Specifically, is it currently possible to control things like charge/discharge rates, force charge windows, and export limits in a way Predbat can reliably use?

Or is GoodWe still mostly read-only / partially exposed for control, meaning Predbat support would be limited or needs significant reverse engineering? Is the current lack of suport just missing mapping for ESA (and we need somebody with ESA to provide the readout), or are there known hard limitations in GoodWe’s local interface?

cheers

**Comment by dmshimself** [comment]
Yes I'd be interested in finding out the current status for goodwe inverters.  I'm happy to have a go if there is a sensible config to start with?

**Comment by dmacwalter** [comment]
> Yes I'd be interested in finding out the current status for goodwe inverters.  I'm happy to have a go if there is a sensible config to start with?

@dmshimself @RampouchCZ — following up my Feb comment about EMS support. I've now got a GoodWe ET hybrid under full Predbat control (charge, forced export, stop) running local-only, no cloud. Here's the whole working config to start from.

This is the EMS path, so it needs [mletenay/home-assistant-goodwe-inverter](https://github.com/mletenay/home-assistant-goodwe-inverter) rather than the core integration, and an inverter that exposes `select.goodwe_ems_mode` and `number.goodwe_ems_power_limit`. Different from @bpinto's setup above, which uses the simpler `eco_charge` / `general` operation modes — if your inverter has no EMS block, follow his instead.

Setup: GoodWe ET hybrid, 22.4 kWh battery, 10 kW inverter, 5.4 kW export limit, Predbat v9.0.3 as an HA add-on.

## Approach

Predbat writes the charge and discharge rates into two `input_number` helpers rather than to the hardware, and scripts do the actual register writes. That leaves exactly one writer on the EMS registers and avoids a race between Predbat and the scripts.

Create two helpers, 0 to your `battery_rate_max` in watts, step 100, box mode:

- `input_number.predbat_charge_rate`
- `input_number.predbat_discharge_rate`

The ceiling must be at least `battery_rate_max`. Mine was capped at 8000 with `battery_rate_max` at 9600 and Predbat's write failed silently.

## apps.yaml

```yaml
  inverter_type: GW
  inverter:
    name: GoodWe ET (custom)
    has_rest_api: false
    has_mqtt_api: false
    has_service_api: true
    output_charge_control: power
    has_charge_enable_time: false
    has_discharge_enable_time: false
    has_target_soc: false
    has_reserve_soc: true
    charge_time_format: S
    charge_time_entity_is_option: false
    soc_units: '%'
    num_load_entities: 1
    has_ge_inverter_mode: false
    has_fox_inverter_mode: false
    time_button_press: false
    clock_time_format: '%d-%m-%y %H:%M:%S'
    write_and_poll_sleep: 2
    has_time_window: false
    support_charge_freeze: true
    support_discharge_freeze: true

  charge_rate:
  - input_number.predbat_charge_rate
  discharge_rate:
  - input_number.predbat_discharge_rate

  charge_start_service:
    service: script.turn_on
    entity_id: script.predbat_charge
    repeat: true
  charge_stop_service:
    service: script.turn_on
    entity_id: script.predbat_stop
    repeat: false
  discharge_start_service:
    service: script.turn_on
    entity_id: script.predbat_export
    repeat: true
  discharge_stop_service:
    service: script.turn_on
    entity_id: script.predbat_stop
    repeat: false
```

`repeat: true` on the start services matters — Predbat re-calls them each cycle, which is how the export setpoint tracks changing PV.

Since `has_time_window: false`, you also need the usual dummy sensors for the schedule entries (`sensor.predbat_GW_0_charge_start_time` and friends) as per the unsupported-inverter guide.

## Scripts

Force charge:

```yaml
predbat_charge:
  alias: Predbat - force charge
  mode: single
  variables:
    setpoint: >-
      {% set rate_max = 9600 %}
      {% set req = states('input_number.predbat_charge_rate') | float(0) %}
      {% set target = rate_max if req <= 0 else [req, rate_max] | min %}
      {{ (((([target, 0] | max) / 100) | round(0) | int) * 100) }}
  sequence:
  - alias: Clear stale mode state, unless already in auto or charging
    if:
    - condition: not
      conditions:
      - condition: state
        entity_id: select.goodwe_ems_mode
        state:
        - auto
        - charge_battery
    then:
    - action: select.select_option
      target:
        entity_id: select.goodwe_ems_mode
      data:
        option: auto
    - delay:
        seconds: 2
  - alias: Power limit first - this is what makes the setpoint stick
    action: number.set_value
    target:
      entity_id: number.goodwe_ems_power_limit
    data:
      value: '{{ setpoint | int }}'
  - action: select.select_option
    target:
      entity_id: select.goodwe_ems_mode
    data:
      option: charge_battery
```

Force export. Same shape plus a clamp: the battery setpoint is reduced by current PV and increased by house load so battery + PV − load stays under the grid export cap. Without it the GoodWe overshoots — I was seeing 5914 W against a 5400 W limit. If PV alone already fills the cap the battery is held rather than discharged.

```yaml
predbat_export:
  alias: Predbat - force export
  mode: single
  variables:
    setpoint: >-
      {% set cap = 5200 %}
      {% set rate_max = 9600 %}
      {% set pv = states('sensor.pv_power') | float(0) %}
      {% set load = states('sensor.house_consumption') | float(0) %}
      {% set req = states('input_number.predbat_discharge_rate') | float(0) %}
      {% set headroom = cap - pv + load %}
      {% set target = headroom if req <= 0 else [req, headroom] | min %}
      {{ ((([[target, 0] | max, rate_max] | min) / 100) | round(0) | int) * 100 }}
  sequence:
  - alias: Clear stale mode state, unless already in auto or a mode we set
    if:
    - condition: not
      conditions:
      - condition: state
        entity_id: select.goodwe_ems_mode
        state:
        - auto
        - discharge_battery
        - battery_standby
    then:
    - action: select.select_option
      target:
        entity_id: select.goodwe_ems_mode
      data:
        option: auto
    - delay:
        seconds: 2
  - alias: PV alone already fills the export cap - hold the battery instead
    if:
    - condition: template
      value_template: '{{ setpoint | float(0) < 200 }}'
    then:
    - action: number.set_value
      target:
        entity_id: number.goodwe_ems_power_limit
      data:
        value: 0
    - action: select.select_option
      target:
        entity_id: select.goodwe_ems_mode
      data:
        option: battery_standby
    - stop: PV is filling the export cap - battery held, not discharged
  - alias: Power limit first - this is what makes the setpoint stick
    action: number.set_value
    target:
      entity_id: number.goodwe_ems_power_limit
    data:
      value: '{{ setpoint | int }}'
  - action: select.select_option
    target:
      entity_id: select.goodwe_ems_mode
    data:
      option: discharge_battery
```

Release to auto, used for both stop services:

```yaml
predbat_stop:
  alias: Predbat - release to auto
  mode: single
  sequence:
  - action: number.set_value
    target:
      entity_id: number.goodwe_ems_power_limit
    data:
      value: 10000
  - action: select.select_option
    target:
      entity_id: select.goodwe_ems_mode
    data:
      option: auto
```

## EMS behaviour worth knowing

Write order matters. The power limit has to be written before the mode, not after — write the mode first and the setpoint does not stick.

The power limit is direction-agnostic magnitude, and the same mode means different things depending on it. At limit 0, `battery_standby` is a genuine hold. At limit 10000, it behaves as a charge request.

Put service keys at the top level, not under a nested `data:` block. Predbat flattens the keys under a service entry into the service data, so a nested block is passed through as a literal key named `data` and HA rejects it with `{'code': 'invalid_format', 'message': "not a valid option at 'data'"}`. The error names the unexpected key, not the value, which is misleading.

Quote every `HH:MM:SS` in apps.yaml. Unquoted times parse as sexagesimal integers under YAML 1.1, so `11:00:00` becomes 39600 and you get `Error: Exception raised 'int' object has no attribute 'count'` out of `basic_rates`. Values starting with a zero survive as strings because the leading zero excludes them from the int resolver, which is why the first `rates_import` entry looks fine and nothing else does.

## Not solved

Freeze export. The EMS mode list (auto, charge_pv, discharge_pv, import_ac, export_ac, conserve, off_grid, battery_standby, buy_power, sell_power, charge_battery, discharge_battery) has no mode meaning "don't charge but do discharge to cover house load", and GoodWe isn't a feed-in-first inverter, so a freeze clips surplus PV. If anyone has characterised `conserve` or `discharge_pv` on an ET I'd be glad to hear it.

`set_reserve_service` isn't wired, so Predbat can't move the reserve. The GoodWe's own on-grid and backup depth-of-discharge settings are the only floors on house discharge.

Happy to answer questions or test changes on real hardware.
