### ISSUE TITLE
Solar power not showing on chart

### ISSUE THREAD

**Issue by Emmoore103** [springfall2008/batpred#1180]
**Describe the bug**
I have added the new pv daily prediction chart and it works except for the PV output line (orange) that is just a flat line.

I made sure the sensor was correct (format - sensor.givtcp_xxxxxxxxxx_pv_power). This I copied from Entities in GivTCP. I checked there was an output to the entity which there is. 

**Expected behavior**
I expect the graph to show actual PV input.

**Predbat version**

7.22.2

**Environment details**

- Givenergy 
- Standard HAOS installer
- GivTCP is in MQTT - not sure if that is relevent.

**Screenshots**
![Screenshot 2024-06-05 095107](https://github.com/springfall2008/batpred/assets/146211806/5e73886d-f514-4972-8ad5-5d1d5ec9869e)

![Screenshot 2024-06-05 095311](https://github.com/springfall2008/batpred/assets/146211806/336165b7-c7e9-446e-9e29-4ee328f0bf1d)

**Log file**
Can you capture a log file from the time of the issue, debug mode is not normally required.
If you are not keeping the full logs then please enable this in appdaemon.yaml (see the installation instruction in the Predbat docs area for details on how to do this)

**Comment by Emmoore103** [comment]
Thank you.
That has done the job.
Interesting that it is understandably jagged due to the passing cloud etc.
I wonder if it would be possible to make an entity that smooths out the graph by some sort of averaging. Probably difficult and not that important. I can at least see generally what is happening.

**Comment by Emmoore103** [comment]
Just to show what I am now getting.

![image](https://github.com/springfall2008/batpred/assets/146211806/84222c47-363e-416c-a5ff-b1fd2b3cbfd3)

I think this is now correct, but any comments greatly appreciated.

**Comment by springfall2008** [comment]
Looks right, you can try a longer average period e.g

    group_by:
      func: avg
      duration: 30m

**Comment by Emmoore103** [comment]
Hi Trefor.

Thank you for confirming and for the code to try.

Brilliant work as always.

Kind regards
Eric

**Comment by gcoan** [comment]
Here's my attempt to get this chart working.

![image](https://github.com/springfall2008/batpred/assets/142018870/eac7fe5e-e49d-49aa-b8ed-455eb94787e6)

The bottom is the 'out of the box' chart showing one PV array which works fine.

But I have 3 arrays so really would like to see all 3 of them on the same chart, the top is the adapted chart showing 2 of my arrays. Once I get this working I can then add the 3rd.
I can include 3 arrays as lines by just duplicating the entity definition in the chart but I really want the array solar generations to be stacked one above each other, but when I do this I end up with the 2 solar, the PV and PV10% values all being stacked which is clearly not right!

The best I have got to is to change the group_by for the predbat_pv_today to 'diff', but this only works for one or other of the predbat_ areas, can't get both to work.

Any ideas @springfall2008 ?

```yaml
type: custom:apexcharts-card
header:
  title: Solar forecast
  show: true
  show_states: true
  colorize_states: true
apex_config:
  chart:
    height: 300px
  tooltip:
    enabled: true
    shared: true
    followCursor: true
all_series_config:
  type: column
graph_span: 24h
span:
  start: day
stacked: true
update_interval: 5m
yaxis:
  - id: capacity
    show: true
    opposite: true
    decimals: 0
    max: 100
    min: 0
    apex_config:
      tickAmount: 10
  - id: kWh
    show: true
    min: 0
    apex_config:
      tickAmount: 10
  - id: header_only
    show: false
series:
  - entity: sensor.g_xxx_pv_power
    name: G Solar Power
    stroke_width: 2
    float_precision: 2
    color: Orange
    yaxis_id: kWh
    unit: kW
    extend_to: now
    show:
      legend_value: true
      in_header: false
  - entity: sensor.h_yyy_pv_power
    name: H Solar Power
    stroke_width: 2
    float_precision: 2
    color: Red
    yaxis_id: kWh
    unit: kW
    extend_to: now
    show:
      legend_value: true
      in_header: false
  - entity: sensor.predbat_pv_today
    name: Forecast
    color: grey
    opacity: 0.3
    stroke_width: 1
    type: area
    group_by:
      func: raw
      duration: 5m
    extend_to: false
    yaxis_id: kWh
    show:
      legend_value: false
      in_header: false
    data_generator: |
      return entity.attributes.detailedForecast.map((entry) => {
            return [new Date(entry.period_start), entry.pv_estimate];
          });
  - entity: sensor.predbat_pv_today
    name: Forecast 10%
    color: grey
    opacity: 0.3
    stroke_width: 1
    type: area
    group_by:
      func: raw
      duration: 5m
    extend_to: false
    yaxis_id: kWh
    show:
      legend_value: false
      in_header: false
    data_generator: |
      return entity.attributes.detailedForecast.map((entry) => {
            return [new Date(entry.period_start), entry.pv_estimate10];
          });
  - entity: sensor.sum_solar_energy_today
    yaxis_id: header_only
    name: Today Actual
    stroke_width: 2
    color: Orange
    show:
      legend_value: true
      in_header: true
      in_chart: false
  - entity: sensor.predbat_pv_today
    yaxis_id: header_only
    name: Today Forecast
    color: Grey
    show:
      legend_value: true
      in_header: true
      in_chart: false
  - entity: sensor.predbat_pv_today
    yaxis_id: header_only
    attribute: remaining
    name: Remaining
    color: Grey
    show:
      legend_value: true
      in_header: true
      in_chart: false
```
