### ISSUE TITLE
If rate is omitted in rates_override then zero is assumed

### ISSUE THREAD

**Issue by gcoan** [springfall2008/batpred#1255]
**Describe the bug**
Playing around with import_rate_override in apps.yaml I omitted a rate or rate_offset, assuming that Predbat would just apply the load offset at the current rate, but this had the undesired effect of setting the rate to zero.

**Expected behavior**
Ability to not include rate or rate_offset and Predbat doesn't change the rate.  This has the advantage of giving another option for people wanting to adjust their future load predictions.

**Predbat version**
8.1.2

**Screenshots**
Apps.yaml:
```yaml
    -  date: '2024-06-27'
       start: '12:00:00'
       end: '14:30:00'
       load_scaling: 1.0
```

Resultant plan:
![image](https://github.com/springfall2008/batpred/assets/142018870/97862c74-1d5a-4216-be19-5d52a0d3ddc7)

**Log file**
[appdaemon.log](https://github.com/user-attachments/files/15994705/appdaemon.log)
