### ISSUE TITLE
Octopus Free Electricity session - reverse saving session

### ISSUE THREAD

**Issue by johnwb87** [springfall2008/batpred#1363]
Just had email from Octopus about this.

It sounds like it is essentially a reverse savings session as it is only the additional usage that is free.

My first thought is to set a force charge during the window nicely in advance and see what predbat decides to do with that.

Any other thoughts?

**Comment by CJDumbleton** [comment]
More background information about free electricity sessions from Octopus here: [https://octopus.energy/free-electricity/](https://octopus.energy/free-electricity/).

**Comment by gcoan** [comment]
I suggest the best way is to treat it as a zero price session, then Predbat will decide based on your solar forecast and predicted load as to whether it should discharge the battery or not.

In apps.yaml, add the following:
```
  rates_import_override:
    -  date: '2024-08-15'
       start: '13:00:00'
       end: '14:00:00'
       rate: 0
       load_scaling: 1.0
```

Increase  load scaling if you expect to put the washing on, etc.

Unfortunately until Octopus provide an API for this, there isn't much automation predbat can do.  I have a semi-automated solution which updates apps.yaml for you based on you setting the date and times in Home Assistant - see https://community.givenergy.cloud/d/3968-automating-octopus-power-up-events-into-predbat
