### ISSUE TITLE
Add support for Energi Data Service

### ISSUE THREAD

**Issue by woopstar** [springfall2008/batpred#1560]
**Is your feature request related to a problem? Please describe.**
Energy Rates are needed to do the calculations. Currently, the UK market is supported.

We could quickly implement Energi Data Service as a provider to enable the DK market.

Everyone heavily uses it in Denmark.

https://github.com/MTrab/energidataservice

**Describe the solution you'd like**
Add support for Energy Data Service with the provided sensors.

**Comment by gcoan** [comment]
Predbat supports different energy rates, not specifically the UK (although yes it was developed in the UK)

https://springfall2008.github.io/batpred/energy-rates/

If you are able to create a template sensor to reformat the Energi Data Service output to one of the formats Predbat already accepts this would make it easier than extending Predbat for specific energy integrations.  Happy to add it to the documentation as an example for other DK users.

**Comment by woopstar** [comment]
@gcoan Can you provide the formats Predbat already accepts? Then I can look into creating a template sensor that reformats Energi Data Service to be supported.

**Comment by woopstar** [comment]
@springfall2008 can you help me out here, so I can try to make a template sensor. Also on what properties they should be used in? I suspect its the `rates_import ` and `rates_export` ?

**Comment by gcoan** [comment]
> @gcoan Can you provide the formats Predbat already accepts? Then I can look into creating a template sensor that reformats Energi Data Service to be supported.

Sorry overlooked responding.

The format of the rates sensor is defined in the documentation for Bottle Cap Dave's Octopus integration. Here's a fragment of the event.octopus_energy_METERID_current_day_rates (import) sensor, the export_current_day_rates is the same:

```
event_types: octopus_energy_electricity_current_day_rates
event_type: octopus_energy_electricity_current_day_rates
rates: 
- start: '2024-11-02T00:00:00+00:00'
  end: '2024-11-02T00:30:00+00:00'
  value_inc_vat: 0.173985
  is_capped: false
- start: '2024-11-02T00:30:00+00:00'
  end: '2024-11-02T01:00:00+00:00'
  value_inc_vat: 0.196245
  is_capped: false
- start: '2024-11-02T01:00:00+00:00'
  end: '2024-11-02T01:30:00+00:00'
  value_inc_vat: 0.178815
  is_capped: false
- start: '2024-11-02T01:30:00+00:00'
  end: '2024-11-02T02:00:00+00:00'
  value_inc_vat: 0.17199
  is_capped: false
```

There's some more attributes after those but I think the key ones are the rates which comprise of start and end time and value.  I have a fixed 15pence export rate and the export rate sensor also repeats all the 30 minute time blocks even though the rate is the same throughout the day.

**Comment by springfall2008** [comment]
> **Is your feature request related to a problem? Please describe.** Energy Rates are needed to do the calculations. Currently, the UK market is supported.
> 
> We could quickly implement Energi Data Service as a provider to enable the DK market.
> 
> Everyone heavily uses it in Denmark.
> 
> https://github.com/MTrab/energidataservice
> 
> **Describe the solution you'd like** Add support for Energy Data Service with the provided sensors.

If you install this service and snapshot what the data is like I maybe able to help?

**Comment by woopstar** [comment]
<img width="882" alt="image" src="https://github.com/user-attachments/assets/c242fcd3-552b-492f-941a-6b5e0a8d458a">

Does this work ?

There is also forecast available in another attribute:

<img width="226" alt="image" src="https://github.com/user-attachments/assets/2383f0e7-ade2-437c-8f81-87e04c108605">

**Comment by scholdan** [comment]
Would be really cool to have this feature! :)

**Comment by scholdan** [comment]
This is not only for Denmark but would work for multiple countries:

<html>
<body>




FIXED PRICE |   | x |  
Belgium |   |   |  
Denmark | x | x | x
Estonia |   |   |  
Finland |   |   |  
France |   |   |  
Latvia |   |   |  
Lithuania |   |   |  
Luxemburg |   |   |  
Netherlands |   |   |  
Norway |   |   |  
Sweden |   |  

<br class="Apple-interchange-newline">
</body>
</html>

I tried making a template

`- sensor:
    - name: "electricity_current_rate"
      state: "ok"
      attributes:
        event_types: >-
          electricity_current_rate
        event_type: >-
          electricity_current_rate
        rates: |
          {% set data = state_attr('sensor.energi_data_service', 'raw_today') %}
          {% if data %}
          {% for item in data %} 
          - start: '{{ item.hour.isoformat() }}'
            end: '{{ (item.hour + timedelta(minutes=30)).isoformat() }}'
            value_inc_vat: {{ item.price }}
            is_capped: false
          - start: '{{ (item.hour + timedelta(minutes=30)).isoformat() }}'
            end: '{{ (item.hour + timedelta(hours=1)).isoformat() }}'
            value_inc_vat: {{ item.price }}
            is_capped: false{% if not loop.last %}{% endif %}{% endfor %}]}
          {% else %}
            {}
          {% endif %}

- sensor:
    - name: "electricity_export_current_rate"
      state: "ok"
      attributes:
        event_types: >-
          electricity_export_current_rate
        event_type: >-
          electricity_export_current_rate
        rates: |
          {% set data = state_attr('sensor.energi_data_service_solceller', 'raw_today') %}
          {% if data %}
          {% for item in data %} 
          - start: '{{ item.hour.isoformat() }}'
            end: '{{ (item.hour + timedelta(minutes=30)).isoformat() }}'
            value_inc_vat: {{ item.price }}
            is_capped: false
          - start: '{{ (item.hour + timedelta(minutes=30)).isoformat() }}'
            end: '{{ (item.hour + timedelta(hours=1)).isoformat() }}'
            value_inc_vat: {{ item.price }}
            is_capped: false{% if not loop.last %}{% endif %}{% endfor %}]}
          {% else %}
            {}
          {% endif %}`
          
          
But i think there is more needed

`2024-12-20 13:20:00.116465: --------------- PredBat - update at 2024-12-20 13:20:00+01:00 with clock skew 0 minutes, minutes now 800
2024-12-20 13:20:00.117155: Saved current settings to /addon_configs/6adb4f0d_predbat/predbat_config.json
2024-12-20 13:20:00.117272: Using cached GITHub data for https://api.github.com/repos/springfall2008/batpred/releases age 21.2 minutes
2024-12-20 13:20:00.117404: Predbat /config/predbat.py version v8.8.10 currently running, latest version is v8.8.10 latest beta v8.8.10
2024-12-20 13:20:00.117430: Autoupdate: Currently up to date
2024-12-20 13:20:00.130870: Configuration: forecast_hours 48 num_cars 0 debug enable is False calculate_plan_every 10
2024-12-20 13:20:00.131134: Predbat mode is set to Monitor
2024-12-20 13:20:00.213757: Found 21600 load_today datapoints going back 0 days
2024-12-20 13:20:00.352360: Car charging hold True threshold 6.0
2024-12-20 13:20:00.352480: Current data so far today: load 1.57 kWh import 73.2 kWh export 0.5 kWh pv 8.9 kWh
2024-12-20 13:20:00.352587: Warn: No Octopus data in sensor sensor.electricity_previous_rate attribute 'all_rates'
2024-12-20 13:20:00.352677: Warn: No Octopus data in sensor event.electricity_current_day_rates attribute 'all_rates' / 'rates' / 'raw_today'
2024-12-20 13:20:00.352692: Error: metric_octopus_import is not set correctly or no energy rates can be read
2024-12-20 13:20:00.366315: Warn: record_status Error: metric_octopus_import not set correctly or no energy rates can be read
2024-12-20 13:20:00.366693: Error: Exception raised 
2024-12-20 13:20:00.367145: Error: Traceback (most recent call last):
  File "/config/predbat.py", line 965, in run_time_loop
    self.update_pred(scheduled=True)
  File "/config/predbat.py", line 535, in update_pred
    self.fetch_sensor_data()
  File "/config/fetch.py", line 825, in fetch_sensor_data
    raise ValueError
ValueError

2024-12-20 13:20:00.381283: Info: record_status Error: Exception raised 
2024-12-20 13:20:00.381510: Error: 
`

**Comment by scholdan** [comment]
This is not only for Denmark but would work for multiple countries:




@springfall2008 I tried making a template, but failed :/

```
- sensor:
    - name: "electricity_current_rate"
      state: "ok"
      attributes:
        event_types: >-
          electricity_current_rate
        event_type: >-
          electricity_current_rate
        rates: |
          {% set data = state_attr('sensor.energi_data_service', 'raw_today') %}
          {% if data %}
          {% for item in data %} 
          - start: '{{ item.hour.isoformat() }}'
            end: '{{ (item.hour + timedelta(minutes=30)).isoformat() }}'
            value_inc_vat: {{ item.price }}
            is_capped: false
          - start: '{{ (item.hour + timedelta(minutes=30)).isoformat() }}'
            end: '{{ (item.hour + timedelta(hours=1)).isoformat() }}'
            value_inc_vat: {{ item.price }}
            is_capped: false{% if not loop.last %}{% endif %}{% endfor %}
          {% else %}
            {}
          {% endif %}

- sensor:
    - name: "electricity_export_current_rate"
      state: "ok"
      attributes:
        event_types: >-
          electricity_export_current_rate
        event_type: >-
          electricity_export_current_rate
        rates: |
          {% set data = state_attr('sensor.energi_data_service_solceller', 'raw_today') %}
          {% if data %}
          {% for item in data %} 
          - start: '{{ item.hour.isoformat() }}'
            end: '{{ (item.hour + timedelta(minutes=30)).isoformat() }}'
            value_inc_vat: {{ item.price }}
            is_capped: false
          - start: '{{ (item.hour + timedelta(minutes=30)).isoformat() }}'
            end: '{{ (item.hour + timedelta(hours=1)).isoformat() }}'
            value_inc_vat: {{ item.price }}
            is_capped: false{% if not loop.last %}{% endif %}{% endfor %}
          {% else %}
            {}
          {% endif %}
```

```
2024-12-20 14:35:01.198233: Warn: No Octopus data in sensor sensor.electricity_previous_rate attribute 'all_rates'
2024-12-20 14:35:01.198393: Warn: No Octopus data in sensor event.electricity_current_day_rates attribute 'all_rates' / 'rates' / 'raw_today'
2024-12-20 14:35:01.198416: Error: metric_octopus_import is not set correctly or no energy rates can be read
2024-12-20 14:35:01.221868: Warn: record_status Error: metric_octopus_import not set correctly or no energy rates can be read
2024-12-20 14:35:01.222005: Error: Exception raised 
2024-12-20 14:35:01.222172: Error: Traceback (most recent call last):
  File "/config/predbat.py", line 965, in run_time_loop
    self.update_pred(scheduled=True)
  File "/config/predbat.py", line 535, in update_pred
    self.fetch_sensor_data()
  File "/config/fetch.py", line 825, in fetch_sensor_data
    raise ValueError
ValueError

2024-12-20 14:35:01.239469: Info: record_status Error: Exception raised 
2024-12-20 14:35:01.239591: Error: 

```

**Comment by scholdan** [comment]
Data from Energi Data Service:

```
state_class: total
current_price: 0.7603168813600001
unit: kWh
currency: DKK
region: West of the great belt
region_code: DK1
tomorrow_valid: true
next_data_update: 13:40:09
today: 0.341, 0.405, 0.389, 0.399, 0.366, 0.321, 0.398, 0.602, 0.537, 0.63, 0.64, 0.646, 0.662, 0.661, 0.676, 0.76, 1.019, 1.503, 1.412, 1.142, 0.996, 0.637, 0.579, 0.534
tomorrow: 0.346, 0.445, 0.438, 0.418, 0.406, 0.424, 0.535, 0.546, 0.562, 0.622, 0.642, 0.637, 0.639, 0.627, 0.59, 0.603, 0.622, 0.956, 0.944, 0.877, 0.826, 0.397, 0.388, 0.386
raw_today: 
- hour: '2024-12-20T00:00:00+01:00'
  price: 0.341
- hour: '2024-12-20T01:00:00+01:00'
  price: 0.405
- hour: '2024-12-20T02:00:00+01:00'
  price: 0.389
- hour: '2024-12-20T03:00:00+01:00'
  price: 0.399
- hour: '2024-12-20T04:00:00+01:00'
  price: 0.366
- hour: '2024-12-20T05:00:00+01:00'
  price: 0.321
- hour: '2024-12-20T06:00:00+01:00'
  price: 0.398
- hour: '2024-12-20T07:00:00+01:00'
  price: 0.602
- hour: '2024-12-20T08:00:00+01:00'
  price: 0.537
- hour: '2024-12-20T09:00:00+01:00'
  price: 0.63
- hour: '2024-12-20T10:00:00+01:00'
  price: 0.64
- hour: '2024-12-20T11:00:00+01:00'
  price: 0.646
- hour: '2024-12-20T12:00:00+01:00'
  price: 0.662
- hour: '2024-12-20T13:00:00+01:00'
  price: 0.661
- hour: '2024-12-20T14:00:00+01:00'
  price: 0.676
- hour: '2024-12-20T15:00:00+01:00'
  price: 0.76
- hour: '2024-12-20T16:00:00+01:00'
  price: 1.019
- hour: '2024-12-20T17:00:00+01:00'
  price: 1.503
- hour: '2024-12-20T18:00:00+01:00'
  price: 1.412
- hour: '2024-12-20T19:00:00+01:00'
  price: 1.142
- hour: '2024-12-20T20:00:00+01:00'
  price: 0.996
- hour: '2024-12-20T21:00:00+01:00'
  price: 0.637
- hour: '2024-12-20T22:00:00+01:00'
  price: 0.579
- hour: '2024-12-20T23:00:00+01:00'
  price: 0.534

raw_tomorrow: 
- hour: '2024-12-21T00:00:00+01:00'
  price: 0.346
- hour: '2024-12-21T01:00:00+01:00'
  price: 0.445
- hour: '2024-12-21T02:00:00+01:00'
  price: 0.438
- hour: '2024-12-21T03:00:00+01:00'
  price: 0.418
- hour: '2024-12-21T04:00:00+01:00'
  price: 0.406
- hour: '2024-12-21T05:00:00+01:00'
  price: 0.424
- hour: '2024-12-21T06:00:00+01:00'
  price: 0.535
- hour: '2024-12-21T07:00:00+01:00'
  price: 0.546
- hour: '2024-12-21T08:00:00+01:00'
  price: 0.562
- hour: '2024-12-21T09:00:00+01:00'
  price: 0.622
- hour: '2024-12-21T10:00:00+01:00'
  price: 0.642
- hour: '2024-12-21T11:00:00+01:00'
  price: 0.637
- hour: '2024-12-21T12:00:00+01:00'
  price: 0.639
- hour: '2024-12-21T13:00:00+01:00'
  price: 0.627
- hour: '2024-12-21T14:00:00+01:00'
  price: 0.59
- hour: '2024-12-21T15:00:00+01:00'
  price: 0.603
- hour: '2024-12-21T16:00:00+01:00'
  price: 0.622
- hour: '2024-12-21T17:00:00+01:00'
  price: 0.956
- hour: '2024-12-21T18:00:00+01:00'
  price: 0.944
- hour: '2024-12-21T19:00:00+01:00'
  price: 0.877
- hour: '2024-12-21T20:00:00+01:00'
  price: 0.826
- hour: '2024-12-21T21:00:00+01:00'
  price: 0.397
- hour: '2024-12-21T22:00:00+01:00'
  price: 0.388
- hour: '2024-12-21T23:00:00+01:00'
  price: 0.386

today_min: 
hour: '2024-12-20T05:00:00+01:00'
price: 0.321

today_max: 
hour: '2024-12-20T17:00:00+01:00'
price: 1.503

today_mean: 0.677
tomorrow_min: 
hour: '2024-12-21T00:00:00+01:00'
price: 0.346

tomorrow_max: 
hour: '2024-12-21T17:00:00+01:00'
price: 0.956

tomorrow_mean: 0.578
use_cent: false
attribution: Data sourced from Energi Data Service and forecast from Carnot
forecast: 
- hour: '2024-12-22T00:00:00+01:00'
  price: 0.237
- hour: '2024-12-22T01:00:00+01:00'
  price: 0.237
- hour: '2024-12-22T02:00:00+01:00'
  price: 0.237
- hour: '2024-12-22T03:00:00+01:00'
  price: 0.237
- hour: '2024-12-22T04:00:00+01:00'
  price: 0.237
- hour: '2024-12-22T05:00:00+01:00'
  price: 0.237
- hour: '2024-12-22T06:00:00+01:00'
  price: 0.349
- hour: '2024-12-22T07:00:00+01:00'
  price: 0.607
- hour: '2024-12-22T08:00:00+01:00'
  price: 0.894
- hour: '2024-12-22T09:00:00+01:00'
  price: 1.044
- hour: '2024-12-22T10:00:00+01:00'
  price: 1.064
- hour: '2024-12-22T11:00:00+01:00'
  price: 1.049
- hour: '2024-12-22T12:00:00+01:00'
  price: 0.986
- hour: '2024-12-22T13:00:00+01:00'
  price: 0.936
- hour: '2024-12-22T14:00:00+01:00'
  price: 0.929
- hour: '2024-12-22T15:00:00+01:00'
  price: 0.981
- hour: '2024-12-22T16:00:00+01:00'
  price: 1.087
- hour: '2024-12-22T17:00:00+01:00'
  price: 1.568
- hour: '2024-12-22T18:00:00+01:00'
  price: 1.659
- hour: '2024-12-22T19:00:00+01:00'
  price: 1.678
- hour: '2024-12-22T20:00:00+01:00'
  price: 1.596
- hour: '2024-12-22T21:00:00+01:00'
  price: 1.096
- hour: '2024-12-22T22:00:00+01:00'
  price: 0.901
- hour: '2024-12-22T23:00:00+01:00'
  price: 0.795
- hour: '2024-12-23T00:00:00+01:00'
  price: 0.63
- hour: '2024-12-23T01:00:00+01:00'
  price: 0.593
- hour: '2024-12-23T02:00:00+01:00'
  price: 0.654
- hour: '2024-12-23T03:00:00+01:00'
  price: 0.616
- hour: '2024-12-23T04:00:00+01:00'
  price: 0.579
- hour: '2024-12-23T05:00:00+01:00'
  price: 0.702
- hour: '2024-12-23T06:00:00+01:00'
  price: 1.038
- hour: '2024-12-23T07:00:00+01:00'
  price: 1.408
- hour: '2024-12-23T08:00:00+01:00'
  price: 1.744
- hour: '2024-12-23T09:00:00+01:00'
  price: 1.829
- hour: '2024-12-23T10:00:00+01:00'
  price: 1.837
- hour: '2024-12-23T11:00:00+01:00'
  price: 1.728
- hour: '2024-12-23T12:00:00+01:00'
  price: 1.577
- hour: '2024-12-23T13:00:00+01:00'
  price: 1.484
- hour: '2024-12-23T14:00:00+01:00'
  price: 1.437
- hour: '2024-12-23T15:00:00+01:00'
  price: 1.489
- hour: '2024-12-23T16:00:00+01:00'
  price: 1.634
- hour: '2024-12-23T17:00:00+01:00'
  price: 2.161
- hour: '2024-12-23T18:00:00+01:00'
  price: 2.308
- hour: '2024-12-23T19:00:00+01:00'
  price: 2.371
- hour: '2024-12-23T20:00:00+01:00'
  price: 2.242
- hour: '2024-12-23T21:00:00+01:00'
  price: 1.689
- hour: '2024-12-23T22:00:00+01:00'
  price: 1.504
- hour: '2024-12-23T23:00:00+01:00'
  price: 1.326
- hour: '2024-12-24T00:00:00+01:00'
  price: 1.125
- hour: '2024-12-24T01:00:00+01:00'
  price: 1.131
- hour: '2024-12-24T02:00:00+01:00'
  price: 1.105
- hour: '2024-12-24T03:00:00+01:00'
  price: 1.062
- hour: '2024-12-24T04:00:00+01:00'
  price: 0.998
- hour: '2024-12-24T05:00:00+01:00'
  price: 1.083
- hour: '2024-12-24T06:00:00+01:00'
  price: 1.448
- hour: '2024-12-24T07:00:00+01:00'
  price: 1.741
- hour: '2024-12-24T08:00:00+01:00'
  price: 2.017
- hour: '2024-12-24T09:00:00+01:00'
  price: 2.062
- hour: '2024-12-24T10:00:00+01:00'
  price: 1.993
- hour: '2024-12-24T11:00:00+01:00'
  price: 1.79
- hour: '2024-12-24T12:00:00+01:00'
  price: 1.633
- hour: '2024-12-24T13:00:00+01:00'
  price: 1.494
- hour: '2024-12-24T14:00:00+01:00'
  price: 1.46
- hour: '2024-12-24T15:00:00+01:00'
  price: 1.521
- hour: '2024-12-24T16:00:00+01:00'
  price: 1.537
- hour: '2024-12-24T17:00:00+01:00'
  price: 1.993
- hour: '2024-12-24T18:00:00+01:00'
  price: 2.078
- hour: '2024-12-24T19:00:00+01:00'
  price: 1.994
- hour: '2024-12-24T20:00:00+01:00'
  price: 1.846
- hour: '2024-12-24T21:00:00+01:00'
  price: 1.306
- hour: '2024-12-24T22:00:00+01:00'
  price: 1.094
- hour: '2024-12-24T23:00:00+01:00'
  price: 1.009
- hour: '2024-12-25T00:00:00+01:00'
  price: 0.85
- hour: '2024-12-25T01:00:00+01:00'
  price: 0.81
- hour: '2024-12-25T02:00:00+01:00'
  price: 0.775
- hour: '2024-12-25T03:00:00+01:00'
  price: 0.686
- hour: '2024-12-25T04:00:00+01:00'
  price: 0.595
- hour: '2024-12-25T05:00:00+01:00'
  price: 0.641
- hour: '2024-12-25T06:00:00+01:00'
  price: 0.959
- hour: '2024-12-25T07:00:00+01:00'
  price: 1.235
- hour: '2024-12-25T08:00:00+01:00'
  price: 1.526
- hour: '2024-12-25T09:00:00+01:00'
  price: 1.705
- hour: '2024-12-25T10:00:00+01:00'
  price: 1.66
- hour: '2024-12-25T11:00:00+01:00'
  price: 1.608
- hour: '2024-12-25T12:00:00+01:00'
  price: 1.578
- hour: '2024-12-25T13:00:00+01:00'
  price: 1.504
- hour: '2024-12-25T14:00:00+01:00'
  price: 1.567
- hour: '2024-12-25T15:00:00+01:00'
  price: 1.603
- hour: '2024-12-25T16:00:00+01:00'
  price: 1.612
- hour: '2024-12-25T17:00:00+01:00'
  price: 2.053
- hour: '2024-12-25T18:00:00+01:00'
  price: 2.137
- hour: '2024-12-25T19:00:00+01:00'
  price: 2.12
- hour: '2024-12-25T20:00:00+01:00'
  price: 1.955
- hour: '2024-12-25T21:00:00+01:00'
  price: 1.437
- hour: '2024-12-25T22:00:00+01:00'
  price: 1.278
- hour: '2024-12-25T23:00:00+01:00'
  price: 1.166
- hour: '2024-12-26T00:00:00+01:00'
  price: 0.987
- hour: '2024-12-26T01:00:00+01:00'
  price: 0.959
- hour: '2024-12-26T02:00:00+01:00'
  price: 0.935
- hour: '2024-12-26T03:00:00+01:00'
  price: 0.798
- hour: '2024-12-26T04:00:00+01:00'
  price: 0.738
- hour: '2024-12-26T05:00:00+01:00'
  price: 0.805
- hour: '2024-12-26T06:00:00+01:00'
  price: 1.036
- hour: '2024-12-26T07:00:00+01:00'
  price: 1.232
- hour: '2024-12-26T08:00:00+01:00'
  price: 1.431
- hour: '2024-12-26T09:00:00+01:00'
  price: 1.512
- hour: '2024-12-26T10:00:00+01:00'
  price: 1.512
- hour: '2024-12-26T11:00:00+01:00'
  price: 1.461
- hour: '2024-12-26T12:00:00+01:00'
  price: 1.38
- hour: '2024-12-26T13:00:00+01:00'
  price: 1.343
- hour: '2024-12-26T14:00:00+01:00'
  price: 1.369
- hour: '2024-12-26T15:00:00+01:00'
  price: 1.422
- hour: '2024-12-26T16:00:00+01:00'
  price: 1.506
- hour: '2024-12-26T17:00:00+01:00'
  price: 1.955
- hour: '2024-12-26T18:00:00+01:00'
  price: 2.069
- hour: '2024-12-26T19:00:00+01:00'
  price: 2.042
- hour: '2024-12-26T20:00:00+01:00'
  price: 1.887
- hour: '2024-12-26T21:00:00+01:00'
  price: 1.386
- hour: '2024-12-26T22:00:00+01:00'
  price: 1.161
- hour: '2024-12-26T23:00:00+01:00'
  price: 1.06
- hour: '2024-12-27T00:00:00+01:00'
  price: 0.895
- hour: '2024-12-27T01:00:00+01:00'
  price: 0.81
- hour: '2024-12-27T02:00:00+01:00'
  price: 0.753
- hour: '2024-12-27T03:00:00+01:00'
  price: 0.62
- hour: '2024-12-27T04:00:00+01:00'
  price: 0.55
- hour: '2024-12-27T05:00:00+01:00'
  price: 0.548
- hour: '2024-12-27T06:00:00+01:00'
  price: 0.803
- hour: '2024-12-27T07:00:00+01:00'
  price: 1.011
- hour: '2024-12-27T08:00:00+01:00'
  price: 1.176
- hour: '2024-12-27T09:00:00+01:00'
  price: 1.244
- hour: '2024-12-27T10:00:00+01:00'
  price: 1.192
- hour: '2024-12-27T11:00:00+01:00'
  price: 1.139
- hour: '2024-12-27T12:00:00+01:00'
  price: 1.082
- hour: '2024-12-27T13:00:00+01:00'
  price: 1.069
- hour: '2024-12-27T14:00:00+01:00'
  price: 1.124
- hour: '2024-12-27T15:00:00+01:00'
  price: 1.127

net_operator: N1
tariffs: 
additional_tariffs:
  transmissions_nettarif: 0.092
  systemtarif: 0.064
  elafgift: 0.951
tariffs:
  '0': 0.056
  '1': 0.056
  '2': 0.056
  '3': 0.056
  '4': 0.056
  '5': 0.056
  '6': 0.167
  '7': 0.167
  '8': 0.167
  '9': 0.167
  '10': 0.167
  '11': 0.167
  '12': 0.167
  '13': 0.167
  '14': 0.167
  '15': 0.167
  '16': 0.167
  '17': 0.502
  '18': 0.502
  '19': 0.502
  '20': 0.502
  '21': 0.167
  '22': 0.167
  '23': 0.167

unit_of_measurement: DKK/kWh
device_class: monetary
icon: mdi:flash
friendly_name: Energi Data Service
```
