### ISSUE TITLE
FR - GivEnergy battery maintenance mode to better assist with SOC recalculations

### ISSUE THREAD

**Issue by thewookiewon** [springfall2008/batpred#1578]
**Is your feature request related to a problem? Please describe.**
GivEnergy batteries are known for the occasional SOC issue if batteries do not frequently get below 50% and stay idle for 30 minutes or longer under than threshold, I'd like to have an option toggle on/off that will force Predbat to on a weekly basis dump the entire battery just before a charge slot.

**Describe the solution you'd like**
 I'd like to have an option toggle on/off that will force Predbat to on a weekly basis dump the entire battery just before a charge slot.

**Describe alternatives you've considered**

Manually execute my above idea which is someitmes hard to remember with a growing family :).

**Additional context**
None

**Comment by gcoan** [comment]
You could achieve what you are asking for by an automation calling the select.predbat_manual controls - setting a series of forced discharges and then a forced idle.

Would need a bit of logic to determine when to kick off the series of forced discharges depending on the SoC level, but this would then be entirely under your control rather than another switch and control to maintain in the core predbat product.

Happy to share your automation in the predbat documentation once done

**Comment by thewookiewon** [comment]
A lot of that is beyond my technical level 😩.

**Comment by gcoan** [comment]
Opportunity to learn then !

Seriously though, there's a lot of good tutorials and videos on Home Assistant and it's not actually that difficult to learn.  I'd recommend the Smart Home Junkie channel on YouTube, he does excellent videos on HA and has a recent series on Jinja and YAML that explain how you can write loops and conditional logic.

Have a look at the predbat documents and in particular understand how the manual predbat controls work, these enable you to instruct Predbat to force a particular task in a half hour slot.

Here's a simple automation that forces Predbat to Idle mode at 3pm and 3:30pm every day (it used to keep discharging just before the peak and this was to stop that behaviour)

You'll need to set the times for the select.predbat_manual_force_discharge control but study this and it should give you the idea of how to force the discharge and then the idle.

Then its a matter of triggering it when you want to, or just run it manually ad-hoc

```
alias: "Predbat: stop 3pm discharge"
description: ""
mode: single
triggers:
  - at: "23:00:00"
    trigger: time
actions:
  - data:
      option: "15:00:00"
    target:
      entity_id:
        - select.predbat_manual_idle
    action: select.select_option
  - delay:
      minutes: 1
  - data:
      option: "15:30:00"
    target:
      entity_id: select.predbat_manual_idle
    action: select.select_option
```
