### ISSUE TITLE
Predbat & Predheat usage of "rates_import" conflict?

### ISSUE THREAD

**Issue by Ashpork** [springfall2008/batpred#1600]
**Describe the bug**
Predheat and predbat appear to be at conflict with their usage of "rates_import".

inserting "rates_import" in the Predbat configuration requires the "rate" to be a [pence value](https://springfall2008.github.io/batpred/energy-rates/#rate-bands-to-manually-configure-energy-rates). 

It appears that predheat will use the rates_import from the predbat portion of the configuration, but I think it treats the values as "£"

I've used the apex charts configuration found in the document.

**Expected behaviour**
I hope not to be spending 11,004 pence on heating in the next 48 hours!

**Predbat version**
v8.5.9

**Environment details**

**Screenshots**
With rates_import treating the rate as pence
![image](https://github.com/user-attachments/assets/b2933e08-8a2b-485d-b018-6d758b869125)
![image](https://github.com/user-attachments/assets/ba1ba342-4961-468d-b69b-1c0c405938ad)

With rates_import treating the rate as "£"
![image](https://github.com/user-attachments/assets/94f40ae5-b635-40b9-bf36-4d1cd7253c0e)
![image](https://github.com/user-attachments/assets/f60c57d9-267a-4adf-af62-63fc92f7f49a)

**Log file**

```
  # Rates as pence
  # rates_import:
  #   -  start: "22:30:00"
  #      end: "01:00:00"
  #      rate: 24.617
  #   -  start: "01:00:00"
  #      end: "06:00:00"
  #      rate: 5.2952
  #   -  start: "06:00:00"
  #      end: "09:30:00"
  #      rate: 24.617
  #   -  start: "09:30:00"
  #      end: "11:30:00"
  #      rate: 14.86
  #   -  start: "11:30:00"
  #      end: "20:30:00"
  #      rate: 24.617
  #   -  start: "20:30:00"
  #      end: "22:30:00"
  #      rate: 14.86

#rates as gbp
  rates_import:
   -  start: "22:30:00"
      end: "01:00:00"
      rate: 0.24617
   -  start: "01:00:00"
      end: "06:00:00"
      rate: 0.52952
   -  start: "06:00:00"
      end: "09:30:00"
      rate: 0.24617
   -  start: "09:30:00"
      end: "11:30:00"
      rate: 0.1486
   -  start: "11:30:00"
      end: "20:30:00"
      rate: 0.24617
   -  start: "20:30:00"
      end: "22:30:00"
      rate: 0.1486
```
