### ISSUE TITLE
Allow DayOfWeek filter in rates_import

### ISSUE THREAD

**Issue by peter-dolkens** [springfall2008/batpred#1926]
My retailer (and I don't believe I'm the only one) charges different rates on the weekend, vs weekdays. I can't see any way with the current `rates_import` configuration options to reflect this accurately in my setup.

**Describe the solution you'd like**
Add an optional `dayOfWeek` property that can accept days of the week in your desired format.

E.G.

```yaml
  rates_import:
  # Weekdays (Monday to Friday)
  - start: "00:00:00"
    end: "07:00:00"
    rate: 0.2526
    dayOfWeek : 1,2,3,4,5
  - start: "07:00:00"
    end: "09:00:00"
    rate: 0.3966
    dayOfWeek : 1,2,3,4,5
  - start: "09:00:00"
    end: "17:00:00"
    rate: 0.3854
    dayOfWeek : 1,2,3,4,5
  - start: "17:00:00"
    end: "20:00:00"
    rate: 0.3966
    dayOfWeek : 1,2,3,4,5
  - start: "20:00:00"
    end: "22:00:00"
    rate: 0.3854
    dayOfWeek : 1,2,3,4,5
  - start: "22:00:00"
    end: "00:00:00"
    rate: 0.2526
    dayOfWeek : 1,2,3,4,5
  # Weekends (Saturday to Sunday)
  - start: "00:00:00"
    end: "00:00:00"
    rate: 0.2526
    dayOfWeek : 6,7
```

**Describe alternatives you've considered**
I believe there's ways to achieve this with additional overrides, but this seems fragile and overly complex
