### ISSUE TITLE
Predbat overwriting FoxESS Modbus sensor

### ISSUE THREAD

**Issue by david00yates** [springfall2008/batpred#1928]
**Describe the bug**
When in Control Charge mode, predbat overwrites the battery charge sensor with a state value of 2600 and blanks the state attributes
This is with the FoxEss Modbus integration

**Expected behaviour**
From what I can work out predbat should be reading this sensor value, not writing to it

**Predbat version**

v8.13.0

**Environment details**

- FoxEss H1-5.0-E-G2 inverter, 2x EP5 batteries
- HAOS running predbat as an add-on
- FoxEss Modbus integration

![Image](https://github.com/user-attachments/assets/780775d7-d9a7-4105-a4cb-5756aeb093a6)

![Image](https://github.com/user-attachments/assets/3ae5026f-4b77-4e7a-aa2f-0eaaa6f9eb9c)

**Log file**

[predbat.log](https://github.com/user-attachments/files/18576612/predbat.log)

**Predbat debug yaml file**

[predbat_debug_16_45_00.yaml.txt](https://github.com/user-attachments/files/18576703/predbat_debug_16_45_00.yaml.txt)

**Comment by david00yates** [comment]
It would be good to understand what the purpose of charge_rate and discharge_rate are. It's not clear from the documentation but it does look like these should be to control the charge rate, in which case I have configured my instance incorrectly.

I'll change the config and update on the results

**Comment by gcoan** [comment]
the charge rate and discharge rate in apps.yaml should point to entities that:

- tell Predbat what the current inverter charge and discharge rate is
- enable Predbat to change the inverter charge and discharge rate 

I can add something more to the documentation if its not clear?

**Comment by WyndStryke** [comment]
This is what I have from the integration (Nathan's FoxESS modbus, since there may be others)


- sensor.bms_charge_rate   (maximum possible charge rate from the BMS - this may further be limited by the inverter, purely a sensor and should not be written to)
- sensor.bms_discharge_rate   (maximum possible discharge rate from the BMS - this may further be limited by the inverter, purely a sensor and should not be written to)
- number.force_charge_power (kW, how to control the charge rate when force-charging, this is the one that predbat should be writing to)
- number.force_discharge_power (kW, how to control the discharge rate when force-discharging, this is the one that predbat should be writing to)
- number.max_charge_current (kW, theoretical maximum from the battery stack, will be further limited by the BMS and inverter)
- number.max_discharge_current (kW, theoretical maximum from the battery stack, will be further limited by the BMS and inverter)
- sensor.battery_charge (kW, instantaneous measurement of what the battery is charging right now, purely a sensor, should not be written to)
- sensor.battery_discharge (kW, instantaneous measurement of what the battery is discharging right now, purely a sensor, should not be written to)
- sensor.inverter_battery_power (kW, instantaneous measurement of what the inverter is drawing or sending to the battery, can be positive or negative, purely a sensor, should not be written to)
- sensor.inverter_power (kW, instantaneous measurement of what the inverter is converting, can be positive or negative, purely a sensor, should not be written to)


So for example, I have a 7kW inverter, my bms charge rate is 35A (currently limited by temperature), and my bms discharge rate is 50A, the max charge current is 50A, the max discharge current is also 50A, but in reality my upper limit is 7kW which is 28A because of the inverter.

**Comment by david00yates** [comment]
For clarity it is Nathan's Modbus integration I am using.

**Comment by springfall2008** [comment]
Do we need support for the charge/discharge rate to be in kW too?

**Comment by WyndStryke** [comment]
Easy to convert between kW and W in a helper, it might already be doing that?  (You mentioned that the kW pv_power sensor which I complained about a couple of weeks ago **https://github.com/springfall2008/batpred/issues/1870** is converted to W in history, so I'm guessing the others are likely to do the same).

I'm using predbat in read-only mode, and it seems to be fine as far as that is concerned.   I can pick up predbat's outputs and use that in my own automations.

I have some doubts about the fox.yaml template, in particular it doesn't let predbat put the inverter into Fox's "feed-in first" mode to allow PV to be directly exported rather than being stored in the battery, and I don't think it sets up all the available sensors. I was going to experiment with that but haven't had time.  It works at a MVP level at least.

**Comment by bfayers** [comment]
The number entities for max charge/discharge current are write-only. You would need to be looking at sensor.invbatcurrent (negative when charging) or sensor.bat_current (negative when discharging) to get the values for instantaneous charge/discharge

As for @gcoan 's comment about these:

> the charge rate and discharge rate in apps.yaml should point to entities that:
>
>   - tell Predbat what the current inverter charge and discharge rate is
>    - enable Predbat to change the inverter charge and discharge rate

I'm really not sure how you could configure those on a fox setup? Personally at the moment I have these settings:
```yaml
  charge_start_service:
    service: select.select_option
    entity_id: select.work_mode
    option: "Force Charge"
  # charge_stop_service:
  #   service: select.select_option
  #   entity_id: select.work_mode
  #   option: "Self Use"
  charge_stop_service:
    service: script.inverter_self_use_40a_charge_discharge #Script to set work mode to Self Use and number.max_charge_current / number.max_discharge_current to 40A.
  charge_freeze_service:
    service: number.set_value
    entity_id: number.max_charge_current
    value: 0
  discharge_freeze_service:
    service: number.set_value
    entity_id: number.max_discharge_current
    value: 0
  discharge_start_service:
    service: select.select_option
    entity_id: select.work_mode
    option: "Force Discharge"

  charge_rate:
    - input_number.force_charge_power_watts
  discharge_rate:
    - input_number.force_discharge_power_watts
  battery_power:
    - sensor.invbatpower
  pv_power:
    - sensor.pv_power
  load_power:
    - sensor.load_power
  soc_kw:
   - sensor.bms_kwh_remaining
  soc_percent:
     - sensor.battery_soc
```

Those input_numbers are helper entities and then I have an automation to sync the watts value from those into the force charge/discharge kW number entities provided by the integration (see here: https://gist.github.com/bfayers/82f5a45155281d187f2758c66872c162)
