### ISSUE TITLE
Feature request: visual representation of 30 minute slots where predbat will charge/discharge

### ISSUE THREAD

**Issue by gavintillott** [springfall2008/batpred#207]
I find it quite difficult to see the individual 30 minute Agile slots where predbat will charge / discharge; is there a way to add to predbat so that this could be visualised, ideally integrated into the Octopus energy rates card:

![image](https://github.com/springfall2008/batpred/assets/127998494/5d1c804f-024f-4ac8-a41f-5f9fdf593255)

**Comment by gcoan** [comment]
I've been thinking the same. The information is in the log files per hour, but it's quite cryptic, g+<, bf- etc

I was thinking something that could be simply graphed, charging, Eco, force discharging and holding charge being the sort of states over time we need to see. Possibly with soc (kw or %) as an optional attribute.
But I like the idea of integrating it into the agile price dashboard card as this is I find the most useful way of seeing the forward agile plan

**Comment by Redding43** [comment]
I agree. I am still getting my head around much of this but it would be great to combine the battery graph with tariff details to more easily see what associated tariff is being used for forced charge and discharge

**Comment by springfall2008** [comment]
I've released a beta of this in the latest version, please see the release notes for details:

https://github.com/springfall2008/batpred/releases/tag/v7.10

![image](https://github.com/springfall2008/batpred/assets/48591903/cee224ad-d669-4896-b27c-caa293a9cab6)

**Comment by gcoan** [comment]
I've just been fiddling around with mashing up some of the Apex charts which could give an alternative view of what predbat is planning on doing.
I've taken the home battery prediction graph, reduced it down to just showing 2 hours of history and the forward 10 hours of predicted activity, and then mashed in some of the energy rates chart

Here's the YAML code for this card:
```
type: custom:apexcharts-card
header:
  show: true
  title: Home Battery Prediction (10 hours)
  show_states: true
  colorize_states: true
graph_span: 12h
span:
  start: minute
  offset: '-2h'
now:
  show: true
yaxis:
  - min: 0
series:
  - entity: predbat.soc_kw_h0
    stroke_width: 1
    curve: smooth
    name: actual
    extend_to: now
    show:
      in_header: raw
  - entity: predbat.soc_kw_best
    stroke_width: 3
    curve: smooth
    name: best
    data_generator: >
      let res = []; for (const [key, value] of
      Object.entries(entity.attributes.results)) { res.push([new
      Date(key).getTime(), value]); } return res.sort((a, b) => { return a[0] -
      b[0]  })
    show:
      in_header: raw
  - entity: predbat.soc_kw_best10
    stroke_width: 1
    curve: smooth
    name: best10
    data_generator: >
      let res = []; for (const [key, value] of
      Object.entries(entity.attributes.results)) { res.push([new
      Date(key).getTime(), value]); } return res.sort((a, b) => { return a[0] -
      b[0]  })
    show:
      in_header: raw
  - entity: predbat.best_charge_limit_kw
    stroke_width: 3
    curve: stepline
    name: charge_limit_best
    type: area
    opacity: 0.2
    data_generator: >
      let res = []; for (const [key, value] of
      Object.entries(entity.attributes.results)) { res.push([new
      Date(key).getTime(), value]); } return res.sort((a, b) => { return a[0] -
      b[0]  })
    show:
      in_header: raw
  - entity: predbat.best_discharge_limit_kw
    stroke_width: 1
    curve: stepline
    name: discharge_best
    data_generator: >
      let res = []; for (const [key, value] of
      Object.entries(entity.attributes.results)) { res.push([new
      Date(key).getTime(), value]); } return res.sort((a, b) => { return a[0] -
      b[0]  })
    show:
      in_header: raw
  - entity: predbat.grid_power_best
    name: power
    stroke_width: 1
    type: area
    opacity: 0.2
    data_generator: >
      let res = []; for (const [key, value] of
      Object.entries(entity.attributes.results)) { res.push([new
      Date(key).getTime(), value*5]); } return res.sort((a, b) => { return a[0]
      - b[0]  })
    show:
      in_header: raw
  - entity: predbat.rates
    stroke_width: 2
    curve: stepline
    name: import
    data_generator: >
      let res = []; for (const [key, value] of
      Object.entries(entity.attributes.results)) { res.push([new
      Date(key).getTime(), value]); } return res.sort((a, b) => { return a[0] -
      b[0]  })
    show:
      in_header: raw
```

And the resultant apex chart, you can see the import rates dropping (in dark green), charging periods in (purple), the soc rising (blue for best and red for best10, but this is overnight so they're the same, so hence appear as a purple line), with charging spikes (light green):
![image](https://github.com/springfall2008/batpred/assets/142018870/8fe56da8-8fb7-41d4-a89b-b3b8d8b63e7b)

**Comment by gcoan** [comment]
I installed the latest beta, 7.10.1, and added the custom charging chart per the readme (neat the way you have fed it with your own custom series and it all *just works*), but its not displaying right.
1. No 'charge' rates displaying, despite them being in the entity attributes 
2. I think because I am forecasting 48 hours ahead as per the advice for agile rates (forecast_plan_hours - 48 ) I am getting all the rates duplicated:

![image](https://github.com/springfall2008/batpred/assets/142018870/a07dd699-d32d-47b0-8a2a-8f8098755ccf)
![image](https://github.com/springfall2008/batpred/assets/142018870/1bd0bba4-bbaa-4d78-a453-884ca63e3571)

here's the card setup:
![image](https://github.com/springfall2008/batpred/assets/142018870/255b732a-f9d6-44a7-9a18-4cbbc1544b97)

part of the attributes from predbat_current_rates_import 👍 
![image](https://github.com/springfall2008/batpred/assets/142018870/d6c2d0eb-2a2e-4419-8a6a-973b991054c4)

**Comment by springfall2008** [comment]
Did you uninstall the original card?

**Comment by gcoan** [comment]
fixed it and re-edited my comment above.  hadn't appreciated that you had forked the code!

**Comment by gcoan** [comment]
Just realised that as the clocks go back, the Octopus rates API is giving TWO 1am and 1:30am slots!
![image](https://github.com/springfall2008/batpred/assets/142018870/822cbc23-b7c2-4871-bed3-dc9d5df5033e)

Most confusing for scheduling things

**Comment by gavintillott** [comment]
@springfall2008, this is exactly what I wanted, awesome work; I'll test it over the next few days. @gcoan you can add <showday: true> to the new card, that'll bring the day back to the display

**Comment by gcoan** [comment]
Ah yes, brilliant, got the dates back.

This does show why I’m seeing so many rows in the predbat output vs the standard display driven off the Octopus API.

The octopus api is giving rates to Sunday 10:30 whereas predbat is predicting up to Tuesday 10pm! Of course those rates don’t exist.  That’s 3 days ahead?

Personally would still like to see import and export on the same dataset, alongside each other. 

And another thing just noticed, my phone must have changed to night mode as all the unpopulated activities are white boxes, not background colour showing through.  Looks very weird

Thanks

**Comment by gcoan** [comment]
Looking at it just now, there's something not quite right.

Maybe the clocks changing at 1am and there being duplicated time slots might explain the second 1:30, but doesn't explain the 5:30 activity - it appears that predbat wants to both charge and discharge in the same 30 minute timeslot.
Doesn't sound right to me?

![image](https://github.com/springfall2008/batpred/assets/142018870/e8023b65-2267-49ea-8996-207ddd18f9a8)
![image](https://github.com/springfall2008/batpred/assets/142018870/0373dabc-88cb-4afd-8b08-8060bfcc5b17)

**Comment by gavintillott** [comment]
This might be correct if you have switch.predbat_calculate_discharge_oncharge set to true - this allows charge and discharge in the same time slot I think.

**Comment by springfall2008** [comment]
Predbat slots go down to 5 minutes so it doesn’t mean they overlap as such but are just within the same 30 minute timeframe

**Comment by gcoan** [comment]
Yes I do have calculate discharge on charge slots set to true, and if predbat is planning down to 5 minutes, that’d explain it.

Thanks

**Comment by gavintillott** [comment]
Off topic formatting Q - why does my card not look like like yours @gcoan? 

![image](https://github.com/springfall2008/batpred/assets/127998494/fb0672e7-acaf-4e12-aaf1-32d83bad432c)

**Comment by springfall2008** [comment]
I've thought about making my own instead, what do you think of this?

![image](https://github.com/springfall2008/batpred/assets/48591903/19eaa211-387c-4819-847b-04c9481fbf77)

**Comment by gavintillott** [comment]
That's really nice @springfall2008. As I'm on Agile, I have days' worth of slots on my card so it would be good to flag those rates that are not yet published, with a crystal ball icon or similar. Also, what does it look like in dark mode?

**Comment by springfall2008** [comment]
I released a first version here: https://github.com/springfall2008/batpred/releases/tag/v7.10.2

Yes I think it's a good idea to flag unknown rates, maybe put them in Itallic or similar.

**Comment by springfall2008** [comment]
I've put unknown rates in italics and with a ? now
I've removed the octopus rates card as I'd prefer not support both.

https://github.com/springfall2008/batpred/releases/tag/v7.10.3

**Comment by Redding43** [comment]
![image](https://github.com/springfall2008/batpred/assets/122637671/324b57f3-ea26-4c0b-b32b-4e0bbc50c1b8)

looks good

Only takes up half the page width but that’s more to do that I can’t get the Lovelace layout card option field to show for dashboards, so can’t use it to render the whole dashboard in a easy way

**Comment by gcoan** [comment]
Sorry late in replying, I think this looks great, more information and takes up less room than the octopus rate card, plus as you say Trefor, one thing less to support.

I’ll install it myself and give it a look

Not forgotten your Q about formatting Gavin

Geoffrey

**Comment by Redding43** [comment]
@springfall2008 , dark mode will need some work

![image](https://github.com/springfall2008/batpred/assets/122637671/69566e24-ef0a-4123-aba5-c12d23107eae)

**Comment by slopemad** [comment]
Suggestion for the Predbat plan card - to perhaps add a column for whether there is car charging planned for that slot?

**Comment by springfall2008** [comment]
Good idea

I think I fixed dark mode in the last release.

**Comment by Redding43** [comment]
@springfall2008 - I see this in dark mode after taking the latest update? Am I doing something wrong?

![image](https://github.com/springfall2008/batpred/assets/122637671/5095cbb4-8037-47e9-b689-0dc47dc5e268)

**Comment by gavintillott** [comment]
Yeah I get the below in v7.10.5 when in dark mode:
![IMG_1997](https://github.com/springfall2008/batpred/assets/127998494/07168a48-3c49-4b0a-a6cb-341768a2ce3f)
![IMG_1998](https://github.com/springfall2008/batpred/assets/127998494/9706f57e-ee30-4f2f-a8a7-c4cef40c4e1e)

**Comment by gcoan** [comment]
> Off topic formatting Q - why does my card not look like like yours @gcoan?

I suspect its because of the view type I have on my dashboard.
I've got it set to "Grid (layout card)" which comes from the layout card HACS front end integrations https://github.com/thomasloven/lovelace-layout-card
Provides 4 excellent new dashboard layout styles.  Grid is particularly useful I find, even if you don't define any formatting of the grid dimensions or columns:
```
  - title: Agile Rates
    path: octopus-agile-rates
    icon: ''
    type: custom:grid-layout
    badges: []
    cards:
      - title: Import rates
        type: custom:octopus-energy-rates-card
        entity: predbat.current_rates_import
        cols: 2
        showday: true
        showpast: false
      - title: Export rates
        type: custom:octopus-energy-rates-card
        entity: predbat.current_rates_export
        cols: 2
        showday: true
        showpast: false
```
