### ISSUE TITLE
Account for baseline calculations for Saving Sessions

### ISSUE THREAD

**Issue by al090187** [springfall2008/batpred#2090]
Octopus Saving Sessions use your baseline usage over the previous 10 equivalent slots to work out your energy "saved" over the session. However, Predbat just adds the extra value to the slot for the full export amount.

E.g. Over the past 10 days I have exported at the full 6kW I am allowed by my DNO, but only on 5 days. Therefore, my baseline "import" is negative 3kWh. If I then export at the full 6kW again during the session, I will only receive the bonus for the extra 3kWh over my baseline. Predbat adds the bonus for the full 6kWh, so predictions are not correct, and neither is the total cost value.

The Octopus Plugin does have a baseline entity, but this is no good for prediction, because it only shows a single value for the first half hour slot, then updates for the second half hour slot. So, you would need to calculate the baseline figure manually from the historic data in HA, or from the API data. Maybe contact this developer as they already have the calculations worked out from the API.

https://savingsessions.streamlit.app/

**Comment by gcoan** [comment]
Agreed, at the moment Predbat doesn't take account of the baseline import/export figure in working out the projected savings.

Is it worthwhile making this change?

In my view, calculating a more accurate figure would be 'better', but since the DFS savings figures have been so low (12/13p), its a bit of a moot improvement as participating in DFS (this year) brings in little real financial benefit.  I've personally not exported anything in the last few sessions as I'd result in emptying the batteries earlier and then have to import later on at a higher rate.  Your example of a 6kW export vs a 3kW baseline is DFS difference of 78p vs 39p.

We are also coming to the end of saving sessions for this year.  There might be one or two more, but probably not many more.  And whether they run next year, we will have to see.

Also a practical aspect of doing a baseline calculation using HA data, you'd need to extend the days history retained. HA default is 10 days history but DFS is calculated over the last 10 weekdays / 4 weekend days.  I purge a lot of my entity history with shorter durations than this to shrink the HA database size.
Ideally would use Long Term Statistics in HA but since this is aggregated to hourly figures they aren't suitable for calculating the half-hourly baseline.
Could get the data from Octopus if Predbat knew your Octopus API key, but adds loads more complexity.

**Comment by Nilogax** [comment]
I've built something to do this (similar method to the Solcast adaptive damping @gcoan). I keep track of export during the peak hours over the previous 10 non saving session days (or 4 weekend days) then work out an adjusted "octopoints per penny" figure for each half hour slot. It's still a manual operation to work out an appropriate single rate to use for the slot, then amend apps.yaml to change the "octopoints per penny" value.

I built this last year when rewards were better and I was on Flux so my export coincided with the typical saving session times. I'm now on IOG so don't export much during the saving session times and with the smaller rewards I'm not sure the extra (attempted) accuracy makes that much difference.

**Comment by headbouyJB** [comment]
Hey @gcoan the good news is that Saving Sessions (or rather the underlying DFS) is year-round now! Of course we would expect the grid conditions to make a 'Saving Session' necessary are more likely in winter, but I'll be opting in for each of them whoever they pop up. 
I think it's been brilliant this winter to have PredBat up and running to decide if, and how much, I export for it.
[New look Demand Flexibility Service to go live next week](https://www.neso.energy/news/new-look-demand-flexibility-service-go-live-next-week)

**Comment by TCWORLD** [comment]
Just wanted to bump this. As far as I can tell predbat doesn't account for the baseline, and reports savings as being all export during the session. 

Particularly in the case of the Flux tariff where the power down sessions keep intersecting with the flux period, the actual savings are rather minimal - my baseline is about 2kWh export so actually we're only talking about 1.7kWh worth of a 3.7kW export being actual savings. That is something that should probably be factored in.

The octopus integration is definitely still providing valid baseline entries for both import and export. They seem to update half way through the session as they are calculated based on half-hourly intervals, so that may need some consideration.

**Comment by gcoan** [comment]
> The octopus integration is definitely still providing valid baseline entries for both import and export. They seem to update half way through the session as they are calculated based on half-hourly intervals, so that may need some consideration.

I think the problem remains the same, the data for predbat to calculate the baseline savings figure - which it would need in advance to consider in the plan - isn't readily available.

Home Assistant entity history is by default not long  enough, and some people (myself included) purge the database actively to reduce data storage.

Long term statistics are aggregated to hourly level so don't have the half hour breakdown you'd need to get an accurate figure.

The Octopus integration doesn't provide it for each half hour slot in advance.

So either Predbat has to interrogate your Octopus import/export history,  or Predbat has to accumulate the data itself which it could,  but whether that is materially worthwhile I feel is debatable

**Comment by TCWORLD** [comment]
@gcoan I believe the octopus integration does provide the first slot in advance, so it must know them ahead of time. But yeah we don't see the second one as the sensor doesn't update on that sensor until the time it is reached.

I'll open an issue on that repo to see if we can get the base lines provided for each half hour slot in advance as e.g. an attribute in the event sensor.

**Comment by TCWORLD** [comment]
In fact the `sensor.octopus_energy_electricity_xxx_xxx_export_octoplus_power_down_baseline` sensor (and corresponding import sensor) already has attributes for:
  
 * "Total baseline":  sum across the whole saving session
 * "Baselines": what we need - a list for each half-hour slot within the session.

These appear ahead of time when the session is joined.

The "Baselines" attribute contains a list of dicts, each with `start`, `end` and `baseline` fields which are two datetime values and a numeric value in kWh respectively.

This is based on the integration tracking its own consumption data, so should be reasonably accurate, and what we need no?

**Comment by TCWORLD** [comment]
Another saving session today. Predbat just auto-joined it, and immediately the two baseline sensors make the data required available:

* Import (`sensor.octopus_energy_electricity_xxx_xxx_octoplus_power_down_baseline`):
    ```
    start: "2026-08-27T17:00:00+00:00"
    end: "2026-08-27T17:30:00+00:00"
    total_baseline: 0.0014444444444444444
    baselines:
      - start: "2026-08-27T17:00:00+00:00"
        end: "2026-08-27T17:30:00+00:00"
        baseline: 0
        is_incomplete_calculation: true
      - start: "2026-08-27T17:30:00+00:00"
        end: "2026-08-27T18:00:00+00:00"
        baseline: 0.0014444444444444444
        is_incomplete_calculation: true
    ```
* Export (`sensor.octopus_energy_electricity_xxx_xxx_export_octoplus_power_down_baseline`):
    ```
    start: "2026-08-27T17:00:00+00:00"
    end: "2026-08-27T17:30:00+00:00"
    total_baseline: 1.727666666666667
    baselines:
      - start: "2026-08-27T17:00:00+00:00"
        end: "2026-08-27T17:30:00+00:00"
        baseline: 1.143888888888889
        is_incomplete_calculation: true
      - start: "2026-08-27T17:30:00+00:00"
        end: "2026-08-27T18:00:00+00:00"
        baseline: 0.5837777777777778
        is_incomplete_calculation: true
    ```

(Note the incomplete marker is because Mondays data is unavailable due to an octopus API issue, so the baseline is not exactly correct, though is still reasonably accurate).
