### ISSUE TITLE
Compare function giving consistently inaccurate data

### ISSUE THREAD

**Issue by discodancerstu** [springfall2008/batpred#2130]
Hi Trefor,

The compare function does not appear to be providing accurate results (for me anyway!); as you can see from the graphs and data below it is consistently under-predicting the cost.

![Image](https://github.com/user-attachments/assets/6a3da430-a978-4546-b0da-c105f3a05952)

Our usage is pretty consistent.

![Image](https://github.com/user-attachments/assets/3040ef19-9e0e-48a1-8cde-a4baf3064452)

System setup
-GivTCP v3 beta
-PredAI
-Dual Gen3 inverters, each with 9.5kw battery

[apps(yaml).txt](https://github.com/user-attachments/files/19387858/apps.yaml.txt)
[predbat.log](https://github.com/user-attachments/files/19387859/predbat.log)
[cc2581ab_predai_2025-03-21T11-02-21.052Z.log](https://github.com/user-attachments/files/19387872/cc2581ab_predai_2025-03-21T11-02-21.052Z.log)

**Comment by gcoan** [comment]
I wouldn't say mine is perfect, but its a reasonably good prediction, and with the heat pump the usage varies day to day anyway:

![Image](https://github.com/user-attachments/assets/9d30c0ab-28c8-4df9-89b8-fec0de5ece2d)

Would be checking your losses firstly to check whether they are sensible, and look at load_scaling because if this is set it will put the prediction off.  Have a look at how accurate your solar prediction is and your blend of PV10/PV50

The compare is just running the predbat prediction engine for each tariff so if your prediction factors are off then that would explain the issue

**Comment by discodancerstu** [comment]
Thanks, yes I agree the usage varies a little but mineis very consistent.

I'm unsure how to look at losses etc, please can you explain?

Also PredAI is regularly adjusting the forecast to 0.0 on the plan for a whole day, I can't seem to understand why.

**Comment by springfall2008** [comment]
Something is wrong with your PredAI data as the predicted load goes down

**Comment by discodancerstu** [comment]
> Something is wrong with your PredAI data as the predicted load goes down

Here is my PredAI yaml:

![Image](https://github.com/user-attachments/assets/754e7468-15bf-4446-8aa8-9bcd2482eb45)

And this is the sensor it is looking at:

![Image](https://github.com/user-attachments/assets/26e17887-c853-4d2b-ba61-3badd87e4558)

As I have dual inverters, this sensor only increments (as the GivTCP sensor decreases for some reason), it does not decrease.

So why would the PredAI predicted load reduce?

**Comment by SwiftRR** [comment]
I have run predai.
It has generally performed well but I alternate its use with the HA standard historical data.

Like you, my predai.yaml is based on that provided my Trefor.
I notice that your starting entity isn't a direct lift from the GE load energy entity. 
But I have 1 inverter.
I obtained an AI prediction chart similar to yours.
I also obtained a temperature chart using my weather compensation sensor for my HP as the source. 
```
sensors:
  - name: sensor.givtcp_ce2218g352_load_energy_today_kwh
    #subtract: sensor.myenergi_zappi_20464051_energy_used_today
    subtract: sensor.myenergi_zappi_20464051_charge_added_session
    days: 14
    incrementing: True
    reset_daily: True
    interval: 30
    units: kWh
    future_periods: 100
    database: True
    reset_low: 1.0
    reset_high: 2.0
    country: UK
    max_age: 365
  - name: sensor.e3_tcu10_x07_outside_temperature
    days: 14
    interval: 30
    incrementing: False
    units: c
```

Rob
