### ISSUE TITLE
Documentation - LuxPower

### ISSUE THREAD

**Issue by brickatius** [springfall2008/batpred#2184]
I've tried to create 'input_text.xxxxxxx' helpers for charge and discharge start and end times - for example as in the 'luxpower.yaml' template as follows:

charge_start_time:
    - input_text.lux_batpred_charge_start

but unless I've got something completely wrong these 'input_text'  don't seem to be writable by Predbat and an error occurs. Wouldn't it be better to use the actual predbat sensor names like this?

charge_start_time:
    - sensor.predbat_LuxPower_0_charge_start_time

You can then write a Home Assistant automation to target the LuxPower inverter start and end time sensors, as follows, whenever the predbat sensor changes. 

alias: Charge Time Change - Start
description: ""
triggers:
  - entity_id:
      - sensor.predbat_LuxPower_0_charge_start_time
    trigger: state
conditions: []
actions:
  - metadata: {}
    data:
      time: "{{ states('sensor.predbat_LuxPower_0_charge_start_time')}}"
    target:
      entity_id: time.lux_ac_charge_start1
    enabled: true
    action: time.set_value
mode: single

It works a treat and you can see the new charge and discharge times in the LuxPower app and online monitoring.

**Comment by gcoan** [comment]
There's certainly something incomplete with the documentation because the template defines using input_text.lux_batpred_discharge_start etc as you say, but then there's no guidance as to what then needs to happen when these input_text's are written to.

Predbat should be able to write to input_text's

But looking at your automation, did you try setting the time.lux_ac_charge_start1 entity id's directly in apps.yaml so predbat can write directly to that entity

Per the documentation, predbat can write to time entities for charge/discharge start/end time https://springfall2008.github.io/batpred/apps-yaml/#schedule although this is a fairly new feature and maybe wasn't there when the luxpower template was developed.

Can you give it a go and if it works, let me know what changes are required to the documentation

Also, if there are other automations required or changes to the template, please flag it up

**Comment by brickatius** [comment]
Hi Geoffrey, 

I’ll certainly give it a go. 
I did have Predbat set up very briefly on another machine which for reasons unrelated to Predbat died without backup. I bought another one and started from scratch. As it was only a couple of weeks ago I do remember having this:

charge_start_time:
   - time.lux_ac_charge_start1

I don’t remember the entities in the integration and consequently the values in the monitoring app or online being changed to reflect the values in Predbat. As a result I just set the AC Charge Start1 to 00:00 and the End1 to 23:59 so that when the Charge Enable switch was turned on it was within a charge window. Likewise for discharge settings. I’ll try with the code above in apps.yaml as above tomorrow in order to confirm whether it works or not. 

LuxPower also has start and end times for what it calls ‘Charge First / Charge Priority  which I believe Predbat calls ’discharge_freeze_service’. As there are no times for this in Predbat I set the start and end times to 00:00 and 23:59 respectively. I think that also needs to be reflected in the documentation. 

Kind regards. 
Richard Wall

**Comment by brickatius** [comment]
Hi Geoffrey, 

 Further to yesterday - apps.yaml settings.
 With this from the LuxPower.yaml template

charge_start_time:
    - input_text.lux_batpred_charge_start
  charge_end_time:
    - input_text.lux_batpred_charge_end

2025-04-02 08:37:42.170735: Warn: Validation of apps.yaml found configuration item 'charge_start_time' element input_text.lux_batpred_charge_start can not be modified
2025-04-02 08:37:42.170828: Warn: Validation of apps.yaml found configuration item 'charge_end_time' element input_text.lux_batpred_charge_end can not be modified
2025-04-02 08:37:42.171511: Error: Validation of apps.yaml found 2 configuration errors

And with this, using the LuxPower entities. 
charge_start_time:
    - time.lux_ac_charge_start1
  charge_end_time:
    - time.lux_ac_charge_end1

2025-04-02 08:49:02.385591: Warn: Validation of apps.yaml found configuration item 'charge_start_time' element time.lux_ac_charge_start1 can not be modified
2025-04-02 08:49:02.385698: Warn: Validation of apps.yaml found configuration item 'charge_end_time' element time.lux_ac_charge_end1 can not be modified
2025-04-02 08:49:02.386402: Error: Validation of apps.yaml found 2 configuration errors

The Web Ui shows this on both occasions 
⚠charge_start_time	
- sensor.predbat_LuxPower_0_charge_start_time = 23:59:00
⚠charge_end_time	
- sensor.predbat_LuxPower_0_charge_end_time = 23:59:00

But.with this and the automations I mentioned yesterday Predbat is happy.
charge_start_time:
  - sensor.predbat_LuxPower_0_charge_start_time
charge_end_time:
  - sensor.predbat_LuxPower_0_charge_end_time

The same also applies to the forced discharge start and end times. 

It would appear that Predbat is not picking up the entities and is always producing the Predbat ones. Is this a bug or should the LuxPower.yaml just be modified to show the predbat sensors?

More: LuxPower does not have any SOC max or state of charge entities in kWh. I created these as Template helpers. 

soc_max_kWh (Maximum capacity = battery capacity in ah x battery voltage)
{{ states("sensor.lux_battery_capacity_ah") |float * states("sensor.lux_battery_voltage_live") | float  / 1000}}

soc_kWh (Maximum capacity as above x battery charge as a %)
{{ states("sensor.lux_battery_capacity_ah") |float * states("sensor.lux_battery_voltage_live") | float * states("sensor.lux_battery") | float / 100000}}

I also created these populated with values from the Inverter Datasheet and then modified with observations from the Inverter flow chart. In my case 4000w and accurate to within 50w from observation.

charge_rate:
    - input_number.lux_target_charge_current_w
  discharge_rate:
    - input_number.lux_target_discharge_current_w

Hope this helps.

Kind regards. 
Richard

**Comment by brickatius** [comment]
Hi Geoffrey, 

If the apps,yaml configuration was working as expected the entries would look like this:-

charge_start_time:
time.lux_ac_charge_start1
charge_end_time:
time.lux_ac_charge_end1
discharge_start_time:
  - time.lux_force_charge_start1
discharge_end_time:
  - time.lux_force_charge_end1

Regards, 
Richard

**Comment by gcoan** [comment]
Hi Richard, thanks for all your many messages !

In the luxpower template it has:

```
  inverter_type: LuxPower
  inverter:
...
    has_charge_enable_time: False
    has_discharge_enable_time: False
```

so this is telling predbat that the luxpower inverter doesn't have a charge and discharge time sensors which I think is why predbat is creating its own entities (e.g. predbat_LuxPower_0_charge_start_time)  and setting them to dummy values

but as identified there are time.lux_ac... sensors so I think we should try using them if we can.  if it doesn't work then we'll go back to the automations you have working and just update the documentation to reflect

so in apps.yaml can you set:


```
    has_charge_enable_time: True
    has_discharge_enable_time: True
```
and

```
  charge_start_time:
    - time.lux_ac_charge_start1
  charge_end_time: 
    - time.lux_ac_charge_end1
discharge_start_time: 
  - time.lux_force_charge_start1
discharge_end_time:
  - time.lux_force_charge_end1
```

and lets see if that works.  If you get apps.yaml validation errors and it works, then great, its just a false validation error.

**Comment by gcoan** [comment]
> > and lets see if that works. If you get apps.yaml validation errors and it works, then great, its just a false validation error.
> > 
> This is essentially how I have mine set up and I still get the validation error. However the start and end times do appear to be getting set by predbat at the appropriate times.
> 
> I have just watched them update and the times set match a planned charge in the plan due to start at 11:30pm. I've also checked the LuxPower Device Monitor and can see those times have also been set on the device itself.
> 
> So despite the validation error it does appear to be working.

OK good news, I thought they should work.  We can sort out the false validation error separately.

If @brickatius confirms he is happy with the changes I will update the template - plus anything else that you both spot as wrong

> I should also add that I didn't previously have the soc_kw and soc_max using helpers, mine were hard coded, so I thought it a good idea to create those helpers. The updated docs say to set them as Power and Measurement, however as they are kWh and not kW they should be created as Energy and Total.

Sorry, late at night, corrected now

**Comment by raldred** [comment]
Sorry I authored the original template, I may have missed providing some entities and automations in the docs, sorry about that. The lux inverter is expecting a different format for start and end times then predbat provides. 

You need input text entities for the charge/discharge start and end times
![Image](https://github.com/user-attachments/assets/8e40c5b6-1846-436b-b4cb-888abee80bec)


Automation to set lux inverter times when predbat changes the inputs
```
alias: Lux Set Charge Start (predbat)
description: ""
mode: single
triggers:
  - entity_id:
      - input_text.lux_batpred_charge_start
    trigger: state
conditions: []
actions:
  - action: time.set_value
    metadata: {}
    data:
      time: "{{ states('input_text.lux_batpred_charge_start')}}"
    target:
      entity_id: time.lux_ac_charge_start1

```

I'll look more in the morning

**Comment by raldred** [comment]
You also need an automation to set the discharge SOC on the inverter because it has independent controls. 

My setup works perfectly with these entries and automations the template changes aren't necessary.

```
alias: Lux Set Discharge Target SOC (predbat)
description: ""
triggers:
  - entity_id:
      - binary_sensor.predbat_exporting
      - number.lux_ac_battery_charge_level
    trigger: state
conditions:
  - condition: state
    entity_id: binary_sensor.predbat_exporting
    state: "on"
actions:
  - action: number.set_value
    metadata: {}
    data:
      value: "{{ states('number.lux_ac_battery_charge_level') }}"
    target:
      entity_id: number.lux_forced_discharge_battery_level
mode: single

```

**Comment by owinwood** [comment]
> Sorry I authored the original template, I may have missed providing some entities and automations in the docs, sorry about that. The lux inverter is expecting a different format for start and end times then predbat provides.
> 
> You need input text entities for the charge/discharge start and end times ![Image](https://github.com/user-attachments/assets/8e40c5b6-1846-436b-b4cb-888abee80bec)
> 
> Automation to set lux inverter times when predbat changes the inputs
> 
> ```
> alias: Lux Set Charge Start (predbat)
> description: ""
> mode: single
> triggers:
>   - entity_id:
>       - input_text.lux_batpred_charge_start
>     trigger: state
> conditions: []
> actions:
>   - action: time.set_value
>     metadata: {}
>     data:
>       time: "{{ states('input_text.lux_batpred_charge_start')}}"
>     target:
>       entity_id: time.lux_ac_charge_start1
> ```
> 
> I'll look more in the morning

I thought the helpers weren't required anymore with LuxPython_DEV adding native time settings? I don't recall what version it was added in, but I believe it's the reason I'm now able to use the time entities directly.

From the readme
"@maegibbons has invested significant time refining time settings. In LUXPython for HA 2023.06, we now have native time settings, so any custom helpers/automations can be removed. We won’t remove the old method immediately, but it will be phased out. Going forward, just add time entities like time.lux_ac_charge_start1."

**Comment by gcoan** [comment]
Predbat has added support for setting time entities directly fairly recently (which wasn't there before), so my take on what you LuxPower users are reporting is that these automations are now no longer required

**Comment by raldred** [comment]
Ahh yes, that's right @gcoan. I've just tested this now. Thanks

As @owinwood suggests, this now works without the need for the text_input entities. Works as expected.

```
    has_charge_enable_time: True
    has_discharge_enable_time: True
```

```
  charge_start_time:
    - time.lux_ac_charge_start1
  charge_end_time:
    - time.lux_ac_charge_end1
  discharge_start_time:
    - time.lux_force_discharge_start1
  discharge_end_time:
    - time.lux_force_discharge_end1
```

There's warnings and validation errors, but they seem to work

![Image](https://github.com/user-attachments/assets/af47c6bd-b82e-4313-bae7-33c3e6a5fa51)

```
11237 | 2025-04-03 11:04:40.832840: Inverter 0 Turning on scheduled export
-- | --
11236 | 2025-04-03 11:04:40.832726: Inverter 0 Wrote scheduled_discharge_enable to True successfully and got on
11235 | 2025-04-03 11:04:40.832465: Switch switch.lux_force_discharge_enable is now on
11234 | 2025-04-03 11:04:28.696807: Inverter 0 Wrote discharge_end_time to 11:31:00 successfully
11233 | 2025-04-03 11:04:17.566132: Inverter 0 Set new export end time to 11:31:00 was 00:00:00
11232 | 2025-04-03 11:04:17.565935: Inverter 0 Wrote discharge_start_time to 11:00:00 successfully
11231 | 2025-04-03 11:04:06.531690: Inverter 0 set new export start time to 11:00:00
11230 | 2025-04-03 11:04:06.531561: Inverter 0 write_and_poll_value: Wrote 11:31:00 to idle_start_time, successfully now 11:31:00
11229 | 2025-04-03 11:03:56.507240: Inverter 0 set new demand (idle) start time to 11:31:00 was 05:30:00
11228 | 2025-04-03 11:03:56.507173: Adjust demand (idle) time computed is 11:31:00-23:59:00
11227 | 2025-04-03 11:03:56.507018: Adjust idle time, charge 00:00:00-00:00:00 discharge 11:00:00-11:31:00
11226 | 2025-04-03 11:03:56.506984: Inverter 0 Adjust force export to True, change times from 00:00:00 - 00:00:00 to 11:00:00 - 11:31:00

```
