### ISSUE TITLE
apps.yaml validation rejects charge/discharge start/end time when using time. sensors

### ISSUE THREAD

**Issue by gcoan** [springfall2008/batpred#2196]
**Describe the bug**
In #2184 have simplifying the LuxPower template to use time sensors which predbat accepts and works fine:

```yaml
  charge_start_time:
    - time.lux_ac_charge_start1
  charge_end_time:
    - time.lux_ac_charge_end1
  discharge_start_time:
    - time.lux_force_discharge_start1
  discharge_end_time:
    - time.lux_force_discharge_end1
```

These are however rejected as invalid by the new apps.yaml validation https://github.com/springfall2008/batpred/issues/2184#issuecomment-2775177854

**Expected behaviour**
time sensors not rejected as invalid in apps.yaml validation

**Predbat version**
8.17

**Environment details**
LuxPower

**Screenshots**
See https://github.com/springfall2008/batpred/issues/2184#issuecomment-2775177854
