### ISSUE TITLE
apps.yaml entity linked to an Incorrect entity in predbat

### ISSUE THREAD

**Issue by SwiftRR** [springfall2008/batpred#2219]
**Describe the bug**

This morning the predbat UI apps.yam; checker came up with this error which I had never seen before.
Last night, I upgraded from v8.17.5 to v8.17.6 
<img width="686" alt="Image" src="https://github.com/user-attachments/assets/ad5a4a19-65ff-48bc-bccb-ed81519cfc3b" />

My apps.yaml does have this entity

In my apps.yaml, I had the lines below:

```yaml
 inverter_type:
    - "GE"
  num_inverters: 1
```

I checked my apps.yaml and the related 'schedule' entities are both givTCP switches, whereas the error line points to a predbat sensor.
apps.yaml:

```yaml
  scheduled_charge_enable:
    - switch.givtcp_{geserial}_enable_charge_schedule
  scheduled_discharge_enable:
    - switch.givtcp_{geserial}_enable_discharge_schedule
```
I commented out the GE line in my apps.yaml and the error message went away. But the incorrect entity was still there.

So 

```yaml
  scheduled_discharge_enable:
    - switch.givtcp_{geserial}_enable_discharge_schedule
```
is linking to:

```yaml
  scheduled_discharge_enable:
    - sensor.predbat_ge_0_scheduled_discharge_enable

```
Both entities have the same friendly name.

The related 'scheduled charge' line in apps.yaml is linked to the correct givTCP entity.

The correct givTCP entity is there and the switch is changing from time to time. There is no activity with the 'ge' entity.

In Devices & Services/entities, I have found 3 'ge' entities which may all be dummy entities.

```yaml
sensor.predbat_ge_0_scheduled_discharge_enable
sensor.predbat_ge_0_idle_end_time
sensor.predbat_ge_0_idle_end_time
```

**Expected behaviour**
Entities in apps.yaml being linked to correct entities in running code. 

**Predbat version**
v8.17.6

**Environment details**

- Inverter and battery setup GE AC3.0 with two 8.2 kWh batteries
- Standard HAOS installer HA 2025.3.4 and 15.0 on Raspberry Pi5

In Devices & Services/Entities I have found 3 'ge' entities which could all be 'dummy entities'

**Screenshots**
See above

**Log file**

**Predbat debug yaml file**
I can provide log files and debug file but I do not think they will help. Predbat is picking up or creating the wrong entities.

Rob
