### ISSUE TITLE
Future Agile rates suggestion

### ISSUE THREAD

**Issue by slopemad** [springfall2008/batpred#223]
At the moment, Predbat assumes unpublished Agile rates are the same as today's rates, and there is an offset function to calculate tomorrow.  Trying to think of how it might be better to do this based on Octopus Watch or the agilepredict twitter account suggestions.

I can see that the overnight rates tonight could be about 18p (whereas last night they were down to 0.5p), so I have created a rates_import_override to deal with this:
  rates_import_override:
    - date: '2023-10-31'
      start: '00:00:00'
      end: '07:00:00'
      rate: 18

But I'll need to remember to delete this at 4pm when tomorrow's Agile rates are out.  The rates offset would be a very crude tool, because the rates beyond overnight will be broadly similar to today anyway, hence creating an override.  If I used the rate offset to add 18p, it would likely hike the Low Threshold very high.

But... I only want this override to apply as long as the real Octopus rates are unpublished.  Perhaps there could be an alternative to rates_import_override which only applies until the actual Agile rates are published, and then the actual rates override the override?  The 'date' field is also probably important, as I wouldn't necessarily want my assumed rates for tomorrow to apply for the day after also?

This will help in situations where you have rates tomorrow which differ wildly from today.

**Comment by springfall2008** [comment]
This seems like a good idea to me, I could do a soft override that only applies to unpublished rates. I think I could also support a offset option in this case e.g. +18 rather than 18.

**Comment by gcoan** [comment]
I’m very new to Agile so don’t have a lot of experience of how the rates change over time.  I’d like predbat to generally get the right direction of the rates rather than need to obsess over a precise prediction.
It would seem to me that:
- evening peak is typically going to be the same all week, except perhaps for really cold periods, so that could default to previous day
- there will be lower prices overnight, rising during the day, price being based on day of week (weekends lower) and weather/solar forecast- so copying yesterdays rate with a +/- offset that could be set programmatically based on day of week/solar/wind forecast if you wanted to get that sophisticated 

Geoffrey

**Comment by kernow** [comment]
I contacted the guy who runs Octopus Watch so see if he had an API for the 48 hour prediction that could be hooked into. Unfortunately it's not something that is available to the public, or paid. Would have been an ideal solution

**Comment by slopemad** [comment]
I guess how far into the future a user would like Predbat to have some knowledge of rates depends on the battery:daily usage ratio.  As we go into winter, my ratio is pretty small, so the view to what rates might look like overnight is important, but I'm not so fussed about what the rates look like at tomorrow breakfast time, that can happily wait until the real rates come out at 4pm.  Someone with a higher battery:demand ratio might want a longer term view.  A soft override set to a particular time (either as an offset, or a fixed figure) would be ideal.  

How I see it:

rate_soft_override:
  - start: '01:00:00'
    end: '05:00:00'
    offset: -1
 (or rate: 14 to fix the rate rather than offset it)

Would be more useful to me than the future rate offset on it's own.  If I could map that to a HA sensor

  offset: number.some_ha_number

Even better - saves editing apps.yaml every day :-). Other users may prefer to create additional rate offset period, if they have more battery capacity.

**Comment by gcoan** [comment]
For me personally it’d be nice to have a better “guess” of the next day rates but it’s not super critical.

My daily house load (with an ASHP) is 2-3 times my 14.8kW battery capacity so I’m typically charging to full overnight and depending on solar and rates doing further charging in the morning or afternoon.  So a long look forward doesn’t really add a lot for me.  In fact I’ve reduced the forecast_hours down to 36 hours from 48 as having 2 days of future dated agile rates in the predbat charging plan was just cluttering the dashboard

**Comment by slopemad** [comment]
So, here's what I've been doing the past few days to model 'day ahead' pricing for Agile, and it's there or there abouts.  How to apply this in Batpred is another matter.

So I take the N2EX Next Day pricing from Nordpool:
https://www.nordpoolgroup.com/en/Market-data1/GB/Auction-prices/UK/Hourly/?view=table
Tomorrow's hourly prices are out at 10am in the morning, making sure I get the GBP prices rather than EUR prices ;-)
Convert the hourly MWh prices to kWh prices by dividing by 1000
Apply the Agile formula, i.e. (1.05 * min((kWh price * 2.2) + P, 95)), I use P = 12 (only applies 4pm-7pm) and then add override rates (see below).
This goes in around 10am, and gets removed around 4pm when the actual Agile rates are out.

How the N2EX rates can be scraped into Predbat and rates applied on an automagic basis, I have no idea.  With tonight's overnight rates being quite pricy, this led to more charging this afternoon to counter it.

```
  rates_import_override:
    - date: '2023-11-09'
      start: '23:00:00'
      end: '00:00:00'
      rate: 20
    - date: '2023-11-10'
      start: '00:00:00'
      end: '01:00:00'
      rate: 20
    - date: '2023-11-10'
      start: '01:00:00'
      end: '02:00:00'
      rate: 22
    - date: '2023-11-10'
      start: '02:00:00'
      end: '06:00:00'
      rate: 20
    - date: '2023-11-10'
      start: '06:00:00'
      end: '07:00:00'
      rate: 23
    - date: '2023-11-10'
      start: '07:00:00'
      end: '08:00:00'
      rate: 26
    - date: '2023-11-10'
      start: '08:00:00'
      end: '09:00:00'
      rate: 29
    - date: '2023-11-10'
      start: '09:00:00'
      end: '10:00:00'
      rate: 30
    - date: '2023-11-10'
      start: '10:00:00'
      end: '11:00:00'
      rate: 25
    - date: '2023-11-10'
      start: '11:00:00'
      end: '12:00:00'
      rate: 20
    - date: '2023-11-10'
      start: '12:00:00'
      end: '13:00:00'
      rate: 19
    - date: '2023-11-10'
      start: '13:00:00'
      end: '15:00:00'
      rate: 20
    - date: '2023-11-10'
      start: '15:00:00'
      end: '16:00:00'
      rate: 21
    - date: '2023-11-10'
      start: '16:00:00'
      end: '17:00:00'
      rate: 38
    - date: '2023-11-10'
      start: '17:00:00'
      end: '18:00:00'
      rate: 40
    - date: '2023-11-10'
      start: '18:00:00'
      end: '19:00:00'
      rate: 37
    - date: '2023-11-10'
      start: '19:00:00'
      end: '20:00:00'
      rate: 23
    - date: '2023-11-10'
      start: '20:00:00'
      end: '21:00:00'
      rate: 22
    - date: '2023-11-10'
      start: '21:00:00'
      end: '22:00:00'
      rate: 21
    - date: '2023-11-10'
      start: '22:00:00'
      end: '23:00:00'
      rate: 20
```
