### ISSUE TITLE
Predicted Load about 50% less than actual

### ISSUE THREAD

**Issue by pacemaker82** [springfall2008/batpred#2520]
**Describe the bug**
If I look at the load in the predbat plan, or the `predbat.load_energy_adjusted` my total kWh for the day is about 7 kWh when in reality I use almost double that (not including battery or car charging).

If I chart out the attribute "Results" from `predbat.load_energy_adjusted` for the entire day I get about 7kWh so doesn't appear to be the actual energy remaining in the entity state. The 23.55 attribute entry reflects the same total kWh value for the day anyway..

<img width="534" alt="Image" src="https://github.com/user-attachments/assets/bbee3287-fe61-4b7e-8e02-bb9941011c2a" />

I am unsure if this is a configuration issue or not. Or I am misreading the plan - I am assuming "load" in the plan is not reduced because solar is covering it, and it is actual house load regardless (minus car or battery charge).

I have the following in apps.yaml

```
  load_today:
    - sensor.givtcp_{geserial}_load_energy_today_kwh

  days_previous:
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8

  days_previous_weight:
    - 0.75
    - 0.75
    - 0.75
    - 0.75
    - 0.75
    - 0.75
    - 0.5
```

**Expected behaviour**
Load forecast to represent a relatively accurate house load average, which in my case is 13-15 kWh every day.

**Predbat version**

8.21.11

**Predbat debug yaml file**
This is important for any plan related issues.

Once you have captured the issue go to the Web UI, in the Dash tab click on **predbat_debug.yaml** and wait 30 seconds for it to download. Select 'keep' if your Web Browser thinks the file is dangerous.

Rename the download file to predbat_debug.yaml.txt and upload it to Github. This will allow your plan to be reproduced and also stores all your settings for review.
