### ISSUE TITLE
What would it take to include Sofar inverters?

### ISSUE THREAD

**Issue by onetoomany** [springfall2008/batpred#395]
I've just upgraded my inverter to Sofar HYD, and keen to have BatPred running for it. What would it take to have BatPred run this inverter as well?

To control the inverter, the best way seems to be through RS485 via Sofar2MQTT.
This gives a number of MQTT topic subsets that cover SOC, grid power, inverter power, house load etc...., and MQTT publish topics to force charge or discharge the battery at variable rates. This is done through a mode called "Passive Mode" on the inverter, which isn't by time of day but is fully controlled by RS485 commands.

I saw the previous post about getting Solax inverters included, and the list of entities needed. Before I complete something similar, question is whether its more use to you in the MQTT topic format or not. Alternatively, as I can name the entities anything I want, would it would be simpler to have a specification that I can name my entities against and this become a more versatile solution?

For example:

Charging: (variable rate)
```
    service: mqtt.publish
    data:
      qos: "1"
      retain: true
      topic: Sofar2mqtt/set/charge
      payload: "3000"
```

Discharging, as above with _Sofar2mqtt/set/discharge_
Auto, again with _Sofar2mqtt/set/auto_ and payload of _"true"_

SOC:
```
    - name: "sofar_inverter_battery_charge"
      state_topic: "Sofar2mqtt/state"
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement
      value_template: > 
        {% if (value_json.battery_power < 32767) %}
        {{ (value_json.battery_power) * 10 }}
        {% else %}
        {{ 0 }}
        {% endif %} 
```

**Comment by onetoomany** [comment]
Battery size - hard wired, as only the SOC is read
Max charge rate - hard wired, but typically 3kw for this inverter / 65A
Max discharge rate - hard wired, but typically 3kw for this inverter / 65A

The inverter has a certain level of battery control in it, with a max discharge of 15% and a max charge of 100%
For force charge or discharge, its a case of sending the MQTT command to start, then sending another command to return to Auto - I can't say charge for 30mins.

SOC: sensor.sofar_inverter_battery_SOC
Battery charge:  sensor.sofar_inverter_battery_charge (W)
Battery discharge:  sensor.sofar_inverter_battery_discharge (W)
Battery power (ie net of the above):  sensor.sofar_inverter_battery_power (W)

Grid power: sensor.sofar_grid_power (W)
System power: sensor.sofar_inverter_system_power (W)
House load: sensor.sofar_house_consumption_power (W)
PV: sensor.sofar_solar_power (W)

Exported energy: sensor.sofar_energy_today_exported (kWh)
Imported energy: sensor.sofar_energy_today_purchase (kWh)
Consumed energy: sensor.sofar_energy_today_consumption (kWh)
PV Total energy: sensor.sofar_energy_today_generation (kWh)

Force charge: switch.sofar_charge_mode_3000 (or 1000, 1500, 2000, 2500 etc..)
Force discharge: switch.sofar_discharge_mode_3000
Force auto: switch.sofar_auto_mode
Force battery save: switch.sofar_auto_saver_mode (i.e. charge from PV but no discharge)
(not sure why these are down as switches not buttons)

**Comment by onetoomany** [comment]
I've managed to get PredBat reading my data and creating a valid plan.
Next steps is to get it to control the inverter.

In the instructions, there are supposed **binary_sensor.predbat_charging** and **binary_sensor.predbat_discharging** that I thought I could create a trigger off to change the state of my inverter - however, these don't seem to exist in my sensors. How can I identify if my inverter should be changing between charging, discharging and auto?

Ideally, I'd use these sensors to start a charge until the sensor switches off again - i.e. if the plan says I need to add 0.5kwh to the battery, the sensor will switch off when I get there rather than at the end of the slot. Is this how they should work?

I'm also not sure what behaviour I'm meant to provide to my inverter for a FreezeChrg and HoldChrg period?
I assume both would map to Battery Save (i.e. don't discharge the battery, but charge with any excess solar if available).

**Comment by springfall2008** [comment]
Can you share your apps.yaml so far so it can be added?

I don't think you want to automate based on the sensors, we would want Predbat to trigger the charge or discharge itself. Can you maybe share an automation that starts/stops charging and discharging and then that can be used to add to Predbat code?

**Comment by onetoomany** [comment]
There are four parts to this:
1. A small ESP8266 and TTL>RS485 circuit as per [https://github.com/cmcgerty/Sofar2mqtt](url), which communicates with HA via MQTT
2. The inverter needs to be put into Passive mode
3. yaml package for converting the MQTT messages to sensors - [sofar_inverter.yaml.txt](https://github.com/springfall2008/batpred/files/13527837/sofar_inverter.yaml.txt)
4. the app.yaml config for PredBat - [apps.yaml.txt](https://github.com/springfall2008/batpred/files/13527836/apps.yaml.txt)


Example commands to start / stop charging are:
```
  - alias: Set inverter to Charge at 3kW
    service: mqtt.publish
    data:
      qos: "1"
      retain: true
      topic: Sofar2mqtt/set/charge
      payload: "3000"

  - alias: Set inverter to Discharge at 2kW
    service: mqtt.publish
    data:
      qos: "1"
      retain: true
      topic: Sofar2mqtt/set/discharge
      payload: "2000"

  - alias: Set inverter to Auto
    service: mqtt.publish
    data:
      qos: "1"
      retain: true
      topic: Sofar2mqtt/set/auto
      payload: "true"

  - alias: Set inverter to Battery Save
    service: mqtt.publish
    data:
      qos: "1"
      retain: true
      topic: Sofar2mqtt/set/auto
      payload: "battery_save"
```
