### ISSUE TITLE
Home Assistant Core Warning for predbat.plan_html

### ISSUE THREAD

**Issue by Bcrutt** [springfall2008/batpred#414]
I noticed this warning for **predbat.plan_html** in the Home Assistant Core Log, is there anything I can do to rectify the issue?

I also included the Octopus Energy errors in the screenshot in case they are part of the predbat warning

![image](https://github.com/springfall2008/batpred/assets/132393335/43af5c11-c86c-45d2-85ec-d5ef2c7a47b8)

![image](https://github.com/springfall2008/batpred/assets/132393335/2085d5c3-69d0-4a96-825e-a77fa36c0735)

**Comment by Bcrutt** [comment]
Forgot to add that I upgraded Predbat to v7.13.22 from v7.13.20 this morning

**Comment by gcoan** [comment]
@Bcrutt I don't get that warning in my HA log, but you may well have a larger forward plan window than me.

Its only a warning that the attribute is so large that it can't be stored in the database.  As Trefor says, it shouldn't be stored long term anyway.

But I did get that warning from the Octopus API for the same reasons, and adding this code (edit for your meter details) to configuration.yaml will filter out both the Octopus and predbat warnings :

```yaml
# Filter out 'message too large' warnings from Octopus API
logger:
  default: warning
  filters:
    homeassistant.components.recorder.db_schema: 
      - "State attributes for sensor.octopus_energy_electricity_<meter details>_export_current_rate exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored"
      - "State attributes for sensor.octopus_energy_electricity_<meter details>_current_rate exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored"
      - "State attributes for predbat.plan_html exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored"
    homeassistant.helpers.entity:
      - "Update of sensor.octopus_energy_electricity_<meter details>_export_previous_accumulative_cost is taking over 10 seconds"
      - "Update of sensor.octopus_energy_electricity_<meter details>_previous_accumulative_cost is taking over 10 seconds"
```
