### ISSUE TITLE
Has nordpool future prices stopped working?

### ISSUE THREAD

**Issue by gcoan** [springfall2008/batpred#576]
**Describe the bug**
I noticed yesterday that the future agile prices for Wednesday were exactly the same as the prices were on Tuesday.

Looking today, Thursdays prices (tomorrow) are the same as today's prices. 

In the logfile the nordpool appears to be working ok.

**Expected behavior**
Tomorrow's prices different from today - not necessarily big differences, but not every half hour price the same 

**Predbat version**
7.14.31

**Environment details**
Haos

**Screenshots**
Tuesday plan:
![image](https://github.com/springfall2008/batpred/assets/142018870/1da92ff4-0b19-4cfc-9913-5e5084c673fe)

Wednesday future plan (taken on Tuesday 1pm):
![image](https://github.com/springfall2008/batpred/assets/142018870/f26ad737-ed77-4432-90fb-36d385a359e0)

Wednesday's plan:
![image](https://github.com/springfall2008/batpred/assets/142018870/093f8333-aeff-4d7f-b37d-562cbdda9c0d)

Thursday's future plan (taken on Wednesday 1:30pm):
![image](https://github.com/springfall2008/batpred/assets/142018870/b513bff7-ec1b-4e42-82ae-723513ddb12b)

**Log file**
Wednesday logfile, nordpool pull appears to be working:
[appdaemon (10).log](https://github.com/springfall2008/batpred/files/13830283/appdaemon.10.log)

**extract from apps.yaml**:
```yaml
  futurerate_url: 'https://www.nordpoolgroup.com/api/marketdata/page/325?currency=GBP'
  futurerate_adjust_import: False
  futurerate_adjust_export: True
  futurerate_peak_start: "16:00:00"
  futurerate_peak_end: "19:00:00"
  futurerate_peak_premium_import: 14
  futurerate_peak_premium_export: 6.5
```
