### ISSUE TITLE
Future price over-rides are marked with ? in predbat plan

### ISSUE THREAD

**Issue by gcoan** [springfall2008/batpred#628]
**Describe the bug**
(Low priority)

There is a power up event tomorrow, so I've created an import rate override in apps.yaml:

```yaml
  rates_import_override:
    -  date: '2024-01-18'
       start: '09:00:00'
       end: '12:00:00'
       rate: 0
```

This works fine, Predbat recognises it in the plan and lets the soc drop beforehand so the battery can be charged for free, but the zero rates are being displayed with a ? in the plan.
![image](https://github.com/springfall2008/batpred/assets/142018870/0970b044-51cb-4053-b4e8-287bea8df9d8)

**Expected behavior**
As these are specified override rates I would expect them not to have the ? against them for future (not yet set) agile rates.

**Predbat version**
7.14.45

**Environment details**
HAOS
