### ISSUE TITLE
Unexpected Predbat 'calibration' status

### ISSUE THREAD

**Issue by SwiftRR** [springfall2008/batpred#856]
**Describe the bug**
An unexpected calibration event. 

**Expected behavior**
No calibration!
I am on the Octopus Agile import tariff and Octopus fixed 15p outgoing tariff. Predbat is very active.
See screenshots below showing the status report, GE battery power profile on 14-03-2024 and a GE notification for low BMS voltage (See attachment) but no calibration report from GE at all!
So would the calibration have been initiated by GE or by Predbat?
I have not contacted GE yet but can do.
The low voltage notification was from the middle of the calibration time and would not have initiated it.

I had set the predbat entities as suggested in the configuration.md. 
input_number.predbat_best_soc_keep was set at 0.5 and I have increased this to 0.7 to represent 4% of my total 16.4 kWh battery storage. 
SOC min is set to 0 and reserve to 4%.
If needed, I can supply more information of my predbat setup.
I was too late to pick up the start.

**Predbat version**
v7.16.7
xxxx

**Environment details**
- Inverter and battery setup: Givenergy AC 3.0 coupled inverter daily chaining to two 8.2 kWh batteries
- Standard HAOS installer or Docker: Raspberry Pi 4.0 operating HA connected to a 500 Gb SSD drive (Samsung T7)
I access Predbat on various Mac devices, iMac, iPhone and iPad.

**Screenshots**
If applicable, add screenshots to help explain your problem. The most useful ones can be your battery chart, the Predbat HTML plan and your current settings in HA.
<img width="1002" alt="2024-03-14 GE calibration status report" src="https://github.com/springfall2008/batpred/assets/68816364/bf3b5d87-55aa-4d64-a54b-5b49d4f3d2be">
<img width="1121" alt="2024-03-14 GE power graph" src="https://github.com/springfall2008/batpred/assets/68816364/eb49994b-f2f9-4280-9e24-b4600f3b7ed2">
<img width="901" alt="2024-03-14 GE status changes" src="https://github.com/springfall2008/batpred/assets/68816364/c8a13485-7509-4500-b5c4-15e66e96f587">

**Log file**
This predbat log picks up the period during which calibration completed at 18:26:30.
[predbat.log.3.txt](https://github.com/springfall2008/batpred/files/14623843/predbat.log.3.txt)
I was too late to pick up the start of this event.

**Comment by gcoan** [comment]
Predbat can't initiate a battery calibration, there's no published API 

What you saw was predbat spotting that your battery was calibrating and so it suspends operation until the calibration has finished. 

It's likely that it was the low voltage error you saw that caused the battery to decide to calibrate itself but normally if the battery gets too low it just does an automatic grid charge. Something to ask givenergy, sorry

**Comment by SwiftRR** [comment]
Thanks. I will check out GE early next week.
What is bizarre is that Predbat changed its status to Calibration at 08:07:10 am
I was notified about a low BMS voltage was 11:29:53 am.
At 08:07:10 am, the BMS voltage was steady and well within range.
So what caused Predbat to change its Status to Calibration at 08:07:10 am?
See relevant screenshots below.
<img width="617" alt="Battery data at start of Predbat calibration" src="https://github.com/springfall2008/batpred/assets/68816364/6a94fd1d-cc4d-4881-b370-f48fec3f58c7">

<img width="621" alt="Battery data at GE Low BMS warning" src="https://github.com/springfall2008/batpred/assets/68816364/0d7f4eb3-3f14-4988-90bd-0bd7eace8267">
<img width="551" alt="2024-03-14 calibration start" src="https://github.com/springfall2008/batpred/assets/68816364/75b1c7e0-57c8-4942-9367-0c40bb542dc7">
<img width="1050" alt="2024-03-14 GE BMS voltage warnings" src="https://github.com/springfall2008/batpred/assets/68816364/2166ff19-2078-45d6-be17-2bb9011f108a">

Thanks

Rob

**Comment by gcoan** [comment]
Predbat sets its status to Calibration when it detects that the inverter is calibrating the battery, which must have happened at around 8:07 or shortly beforehand.

The calibration does a full discharge then a full charge, so my mistake, the BMS under voltage is when the battery is fully discharged from the calibration,  so its a consequence of the calibration, not the cause.

Interesting looking in my own notifications, I have two inverters that both had to be calibrated after a new battery was installed.  On one inverter there were no notifications durng the calibration, on the other there was both a BMS under voltage and a BMS over voltage during the calibration - presumably as the inverter finds out what the battery low and high limits are.

No clue as to why the inverter decided to do the calibration though

**Comment by springfall2008** [comment]
I've heard on the forums that because of the lack of error checking on modbus it's possible that a register write when corrupted can trigger a calibration.

**Comment by SwiftRR** [comment]
Interesting – so it isn't just me!

Unfortunately my predbat log for the start of the calibration (08:10 on 14-03-2024) is no longer on HA (unless there is a way for me to retrieve it).
I have experienced this calibration behaviour twice now, on 12-02-2024 and 14-03-2024. I started using predbat on 30-01-2024.
Any data for 12-02-2024 has long since been swallowed up by HA.

So would the corruption have come from predbat or from a deficiency in the GE modbus?
Is there anything that can be done from the predbat end to prevent any future unexpected calibrations?
I am going to quiz GE about this. The inverter firmware is ancient, nearly 2 years old, with no opportunity for me to update it, although GE KB indicates that there have been several updates. Apparently GE are supposed to be drip feeding these through to AC3.0 coupled users.

With 2 batteries, I do find that their SOCs drift out of sync, with the secondary battery always being a little behind. There is supposed to an OCV that gets them back together when the batteries get to their SOC extremes but this takes about 30 min. Could predbat be preventing this (or could it allow 30 min if it finds that the batteries have drifted apart)? 
This is readable in givtcp.   

I also have some errors listed in my other recent predbat issue #857 Random errors and warnings.
Could these be related?

Thanks

Rob

**Comment by gcoan** [comment]
Its worth you updating your appdaemon.yaml to save more (and longer) log files so they don't get overwritten so quickly

eg

```
# write log records to a file, retaining 9 versions, rather than the standard appdaemon log
logs:
  main_log:
    filename: /homeassistant/appdaemon/appdaemon.log
    log_generations: 9
    log_size: 10000000
```

see https://springfall2008.github.io/batpred/install/#appdaemon-install

**Comment by SwiftRR** [comment]
Thanks. Done

Rob

**Comment by SwiftRR** [comment]
Is it worth updating the appdaemon.yaml file in the templates folder so that it matches the example config in the documentation, which doesn't have the log_generations line?

Rob

**Comment by SwiftRR** [comment]
I have done this but I have now lost predbat completely.
The plan states 'null' and all the charts have disappeared with error messages.
I have restarted my inverted again!


The status report is:
<img width="901" alt="image" src="https://github.com/springfall2008/batpred/assets/68816364/6d3fee07-2199-49e0-8303-d2ee89b3e708">
My predbat log is:
[predbat-4.log](https://github.com/springfall2008/batpred/files/14636264/predbat-4.log)

My original appdaemon.yaml is:
[appdaemon.yaml.txt](https://github.com/springfall2008/batpred/files/14636275/appdaemon.yaml.txt)
This was the only file that I changed.

I have changed predbat to 'read only' for the time being and let my inverter take control again until this is fixed.

I have copied back my original appdaemon.yaml file which got installed when I set up predbat. I set up the joint appdaemon/predbat installation.
[appdaemon.yaml.txt](https://github.com/springfall2008/batpred/files/14636634/appdaemon.yaml.txt)


So please help! I need my predbat back!

Rob

**Comment by gcoan** [comment]
Have you tried restarting appdaemon after changing the appdaemon.yaml?

**Comment by gcoan** [comment]
Looking at your appdaemon.yaml, it looks fine, I don't think that's the cause of your issue.

In the logfile it looks like predbat is running fine and then about 11:40 it gets a REST error talking to the inverter and then it just falls in a heap repeatedly.

Predbat has two ways to talk to GivTCP, either by REST which is more efficient or by manipulating the GivTCP Home Assistant entities.  Both can be setup in apps.yaml and if the REST call fails Predbat will fallback to using the non-rest approach.
Do you have the non-rest GivTCP controls configured for your inverter?

I notice there is a warning message about givtcp2 not being evaluated, I assume you don't have two inverters.  The GivTCP2 line should be commented out and all lines referring to it in apps.yaml.

Suggest to get predbat back you shutdown and restart GivTCP which should hopefully restore the REST connection to it. Then lets look at your apps.yaml config

**Comment by SwiftRR** [comment]
I'm back up so immediate panic over.
I had tried restarting everything after any changes.

I have just come off from a  1 hour phone call to GE.
It seemed that my inverter had dropped off line. I couldn't access it from apps or the GE portal.
Their first fix was to reboot my router. I had no faith in this but it worked! I could then access the inverter again through GE apps and portal and predbat leapt back to life.

I also broached the unexpected calibration and they had no idea why these had happened. I see that you have another sufferer of this 'feature'. Could it be initiated by a sequence of Predbat requests? I only discovered this myself as I was checking my system before a saving session, only to find that I was importing! Then I found the earlier event on 12th Feb.

I have checked my apps.yaml file and found a line:    
- http://192.168.1.239:6345  
- http://192.168.1.239:6346  
This matched what Trefor had in his video.
But I do have num_inverters: 1
I think there are lines to initiate controls for not using REST.
I have commented out lines that look like for a 2nd inverter.
I have attached my apps.yaml file so that you can see if there are any other rogue entries.
[apps.yaml.txt](https://github.com/springfall2008/batpred/files/14638052/apps.yaml.txt)

My appdaemon.yaml looks like the set up for the old separate appdaemon/predbat  installation.
I think the file paths need changing to match my configuration.
If I do this, would I change the paths for app_dir and filename: 
app_dir:  /addon_configs/46f69597_appdaemon-predbat/apps
filename: /addon_configs/46f69597_appdaemon-predbat/predbat.log

But I am wary about changing these as it coincided with my inverter going off line!

Since predbat coming back, I am still getting some random errors. See iPhone screenshot below
![IMG_1237](https://github.com/springfall2008/batpred/assets/68816364/76b92668-a101-4860-acbe-d8a2acd0e6a9)

Now to watch Trefor's installation video for the nth time ...

Rob

**Comment by gcoan** [comment]
The inverter going offline would be the cause of the REST errors you saw in the predbat log.  You should also see errors in the GivTCP log.   There's a GivTCP error detector (and a predbat one) I wrote in the Output data part of the docs that will alert you if GivTCP stops working.

Looking at your apps.yaml, there are several entries that are not valid YAML and will cause you problems.

A sub-entity has to be indented by two spaces under the YAML heading so:

```
  reserve:
    - number.givtcp_{geserial}_battery_power_reserve
#    - number.givtcp2_{geserial2}_battery_power_reserve
```

is valid YAML but

```
  inverter_mode:
   - select.givtcp_{geserial}_mode
```

is not

Here's the entries I spotted as being invalid:

```
  givtcp_rest:
   - http://192.168.1.239:6345

  inverter_mode:
   - select.givtcp_{geserial}_mode
#   - select.givtcp2_{geserial2}_mode
  inverter_time:
   - sensor.givtcp_{geserial}_invertor_time
#   - sensor.givtcp2_{geserial2}_invertor_time
  charge_start_time:
   - select.givtcp_{geserial}_charge_start_time_slot_1
#   - select.givtcp2_{geserial2}_charge_start_time_slot_1
  charge_end_time:
   - select.givtcp_{geserial}_charge_end_time_slot_1
#   - select.givtcp2_{geserial2}_charge_end_time_slot_1
  charge_limit:
   - number.givtcp_{geserial}_target_soc
#   - number.givtcp2_{geserial2}_target_soc
  scheduled_charge_enable:
   - switch.givtcp_{geserial}_enable_charge_schedule
#   - switch.givtcp2_{geserial2}_enable_charge_schedule
  scheduled_discharge_enable:
   - switch.givtcp_{geserial}_enable_discharge_schedule
#   - switch.givtcp2_{geserial2}_enable_discharge_schedule
  discharge_start_time:
   - select.givtcp_{geserial}_discharge_start_time_slot_1
#   - select.givtcp2_{geserial2}_discharge_start_time_slot_1
  discharge_end_time:
   - select.givtcp_{geserial}_discharge_end_time_slot_1
#   - select.givtcp2_{geserial2}_discharge_end_time_slot_1

  # Inverter max AC limit (one per inverter). E.g for a 3.6kw inverter set to 3600
  # If you have a second inverter for PV only please add the two values together
  inverter_limit:
   - 8000 
```

there's a rogue - 3680 that should be commented out or export_limit put in (if you have one):

```
 # Export limit is a software limit set on your inverter that prevents exporting above a given level
  # When enabled Predbat will model this limit
  #export_limit:
   - 3680
  # - 3000
```

The sanity check errors in predbat status point to something like a duplicate apps.yaml or predbat.py file, but would need to see the logfile to have a better idea.  It might be these apps.yaml issues as well.

Finally the question about pathnames.  The logfile doesn't really matter, as long as it points to somewhere you can find the logfile it can be whatever you want.  The app_dir should be where appdaemon can find the apps to run.  Maybe this is the cause of the sanity check errors if its finding a duplicate file?
