### ISSUE TITLE
Export Triggers triggering without time lapsed

### ISSUE THREAD

**Issue by pacemaker82** [springfall2008/batpred#870]
**Describe the bug**
Export triggers are triggered but not for the time set in the config "minutes of export needed". 

**Expected behavior**
```
  # Export triggers:
  # For each trigger give a name, the minutes of export needed and the energy required in that time
  # Multiple triggers can be set at once so in total you could use too much energy if all run
  # Creates an entity called 'binary_sensor.predbat_export_trigger_<name>' which will be turned On when the condition is valid
  # connect this to your automation to start whatever you want to trigger

  export_triggers:
     - name: 'large'
       minutes: 60
       energy: 1.0
```

Based on this explanation, I am expecting the "large" trigger to happen when export _energy_ is 1.0 kWh or above _for 60 minutes_. Instead it is being triggered to (on) but am unclear how, my export at the given time was 0.1 kWh

<img width="553" alt="Screenshot 2024-03-18 at 12 37 23" src="https://github.com/springfall2008/batpred/assets/157808562/8c76d6ad-0c5a-4a76-a331-b442469bb6da">

<img width="805" alt="Screenshot 2024-03-18 at 12 38 49" src="https://github.com/springfall2008/batpred/assets/157808562/96bcddc8-49d4-4911-8c85-e46a503d3362">

It on/off seems to be aligned close-ish with export spikes over 1kW power (not energy)

<img width="1003" alt="Screenshot 2024-03-18 at 12 44 58" src="https://github.com/springfall2008/batpred/assets/157808562/e287d476-172b-4cb7-af7f-49649a12f680">

**Predbat version**

7.16.8

**Environment details**

- Inverter and battery setup: AC 3 / 9.5 kWh batt GE
- Standard HAOS installer or Docker: HAOS
- Anything else?

**Screenshots**
above
