### ISSUE TITLE
input_number.predbat_car_charging_plan_max_price wont go negative

### ISSUE THREAD

**Issue by SteveJack34** [springfall2008/batpred#918]
With tomorrows extend period of negative on Agile thought I would set input_number.predbat_car_charging_plan_max_price to -2p to get the most benefit and charge the car at the best prices. 
I have to type a number into input_number.predbat_car_charging_plan_max_price I can't use the up and down arrows and when it chooses when to charge it still seems to be using 0p as the minimum price.

![image](https://github.com/springfall2008/batpred/assets/115835413/f1646f5a-8a76-48ba-b0a0-308ea2415c7d)

**Comment by gcoan** [comment]
As a quick fix, change line 472 of predbat.py, the "min" value to say -10:

```yaml
   {
        "name": "car_charging_plan_max_price",
        "friendly_name": "Car Charging Plan max price",
        "type": "input_number",
        "min": 0,
        "max": 99,
        "step": 1,
        "unit": "p",
        "icon": "mdi:ev-station",
        "default": 0,
    },
```
