### ISSUE TITLE
values in predbat entities do not match values in configured entities

### ISSUE THREAD

**Issue by jacekowski** [springfall2008/batpred#998]
I have the following configuration:

```
  inverter_type: MINE
...
  scheduled_charge_enable:
    - switch.schedule_charge
  scheduled_discharge_enable:
    - switch.schedule_discharge

```

values in  switch.schedule_charge does not match the value in sensor.predbat_mine_0_scheduled_charge_enable (in fact, it seems to be stuck on ON all the time).

Similiar with discharge entities.
